-- MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_HOSPITAL_ADMITS.sql
-- RM 2025.02.25 - Creation
--               - There is no clear delimiter for the 90 days-cap, but there's a PK, so I'm using MERGE 

USE WAREHOUSE MCHS_CUSTOM_XLARGE_WH;
USE DATABASE MCHS_CUSTOM_DB;
USE SCHEMA SPRUCE;

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_HOSPITAL_ADMITS;
CREATE OR REPLACE PROCEDURE MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_HOSPITAL_ADMITS()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS 
$$
var sql_0 = `MERGE INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_HOSPITAL_ADMITS TRG
                  USING MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_HOSPITAL_ADMITS SRC
                     ON TRG.NCHS_ONLY_ENCOUNTER_ID = SRC.NCHS_ONLY_ENCOUNTER_ID
                     AND TRG.NCHS_ONLY_SURGICAL_CASE_ID = SRC.NCHS_ONLY_SURGICAL_CASE_ID
             WHEN MATCHED THEN UPDATE SET 
                    NCHS_ONLY_PERSON_ID = SRC.NCHS_ONLY_PERSON_ID,
                    NCHS_ONLY_MRN = SRC.NCHS_ONLY_MRN,
                    NCHS_ONLY_ENCOUNTER_ID = SRC.NCHS_ONLY_ENCOUNTER_ID,
                    NCHS_ONLY_ENCOUNTER_TYPE = SRC.NCHS_ONLY_ENCOUNTER_TYPE,
                    NCHS_ONLY_FIN = SRC.NCHS_ONLY_FIN,
                    NCHS_ONLY_ENCOUNTER_TS = SRC.NCHS_ONLY_ENCOUNTER_TS,
                    NCHS_ONLY_SURGERY_START_TS = SRC.NCHS_ONLY_SURGERY_START_TS,
                    NCHS_ONLY_DAYS_SINCE_SURGERY = SRC.NCHS_ONLY_DAYS_SINCE_SURGERY,
                    NCHS_ONLY_SURGICAL_CASE_ID = SRC.NCHS_ONLY_SURGICAL_CASE_ID,
                    OR_SURGICAL_CASE_IDENTIFIER = SRC.OR_SURGICAL_CASE_IDENTIFIER,
                    OR_ENCOUNTER_IDENTIFIER = SRC.OR_ENCOUNTER_IDENTIFIER,
                    HOSPITAL_ENCOUNTER_IDENTIFIER = SRC.HOSPITAL_ENCOUNTER_IDENTIFIER,
                    HOSPITAL_ADMIT_INPATIENT_TS = SRC.HOSPITAL_ADMIT_INPATIENT_TS,
--                    DW_CREATE_TS = SRC.DW_UPDATE_TS,
                    DW_UPDATE_TS = SRC.DW_UPDATE_TS
             WHEN NOT MATCHED THEN INSERT (NCHS_ONLY_PERSON_ID, NCHS_ONLY_MRN, NCHS_ONLY_ENCOUNTER_ID, NCHS_ONLY_ENCOUNTER_TYPE, 
                                           NCHS_ONLY_FIN, NCHS_ONLY_ENCOUNTER_TS, NCHS_ONLY_SURGERY_START_TS, NCHS_ONLY_DAYS_SINCE_SURGERY, 
                                           NCHS_ONLY_SURGICAL_CASE_ID, OR_SURGICAL_CASE_IDENTIFIER, OR_ENCOUNTER_IDENTIFIER, 
                                           HOSPITAL_ENCOUNTER_IDENTIFIER, HOSPITAL_ADMIT_INPATIENT_TS, DW_CREATE_TS, DW_UPDATE_TS)
                                   VALUES (SRC.NCHS_ONLY_PERSON_ID, SRC.NCHS_ONLY_MRN, SRC.NCHS_ONLY_ENCOUNTER_ID, SRC.NCHS_ONLY_ENCOUNTER_TYPE, 
                                           SRC.NCHS_ONLY_FIN, SRC.NCHS_ONLY_ENCOUNTER_TS, SRC.NCHS_ONLY_SURGERY_START_TS, SRC.NCHS_ONLY_DAYS_SINCE_SURGERY, 
                                           SRC.NCHS_ONLY_SURGICAL_CASE_ID, SRC.OR_SURGICAL_CASE_IDENTIFIER, SRC.OR_ENCOUNTER_IDENTIFIER, 
                                           SRC.HOSPITAL_ENCOUNTER_IDENTIFIER, SRC.HOSPITAL_ADMIT_INPATIENT_TS, SRC.DW_UPDATE_TS, SRC.DW_UPDATE_TS); `;
try {
    var stmt = snowflake.createStatement ( {sqlText:sql_0} );
    stmt.execute();
    rowCount = stmt.getNumRowsAffected();    
    return "Number of records affected: " + rowCount ;
    }
catch(err) {
           throw "Error Occurred: " + err.message;
           }
$$;


CALL MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_HOSPITAL_ADMITS()
-- Successful 2025.02.25
-- Number of records affected: 10,429
-- 00:00:02
 
SELECT COUNT(*) AS COUNT
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_HOSPITAL_ADMITS; -- 10,429, mostly loaded manually previously 

