-- MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_ADMIN_MEDS.sql
-- RM 2025.02.10 - Creation
--               - This SP needs a delete/re-insert strategy, as there is no PK for the UPDATE statement.

USE WAREHOUSE MCHS_CUSTOM_XLARGE_WH;
USE DATABASE MCHS_CUSTOM_DB;
USE SCHEMA SPRUCE;

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS;

CREATE OR REPLACE PROCEDURE MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_ADMIN_MEDS()
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS 
$$
var sql_tmp = `CREATE TEMPORARY TABLE MCHS_CUSTOM_DB.SPRUCE.TEMP_SURGICAL_CASE_OR_ADMIN_MEDS AS (
               SELECT MEDS.NCHS_ONLY_PERSON_ID, MEDS.NCHS_ONLY_MRN, MEDS.NCHS_ONLY_ENCOUNTER_ID, MEDS.NCHS_ONLY_FIN, 
                      MEDS.NCHS_ONLY_SURGICAL_CASE_ID, MEDS.NCHS_ONLY_ORDER_ID_SEQUENCE, MEDS.NCHS_ONLY_ORDER_PROVIDER_ID, 
                      MEDS.OR_SURGICAL_CASE_IDENTIFIER, MEDS.OR_ENCOUNTER_IDENTIFIER, MEDS.MEDICATION_NAME, MEDS.MEDICATION_ROUTE, 
                      MEDS.MEDICATION_ROUTE_MAPPED, MEDS.MEDICATION_ADMINISTRATION_TS, MEDS.DW_UPDATE_TS
               FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ADMIN_MEDS MEDS
               JOIN MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR               SCOR
                 ON SCOR.NCHS_ONLY_ENCOUNTER_ID = MEDS.NCHS_ONLY_ENCOUNTER_ID
                AND SCOR.NCHS_ONLY_SURGICAL_CASE_ID = MEDS.NCHS_ONLY_SURGICAL_CASE_ID 
               WHERE DATEDIFF(DAY, SCOR.SURGERY_START_TS::DATE, CURRENT_TIMESTAMP::DATE) <= 90);`;
var sql_del = `DELETE FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS
               WHERE NCHS_ONLY_SURGICAL_CASE_ID IN (
               SELECT NCHS_ONLY_SURGICAL_CASE_ID
               FROM MCHS_CUSTOM_DB.SPRUCE.TEMP_SURGICAL_CASE_OR_ADMIN_MEDS);`;
var sql_ins = `INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS
               SELECT NCHS_ONLY_PERSON_ID, NCHS_ONLY_MRN, NCHS_ONLY_ENCOUNTER_ID, NCHS_ONLY_FIN, NCHS_ONLY_SURGICAL_CASE_ID, 
                      NCHS_ONLY_ORDER_ID_SEQUENCE, NCHS_ONLY_ORDER_PROVIDER_ID, OR_SURGICAL_CASE_IDENTIFIER, 
                      OR_ENCOUNTER_IDENTIFIER, MEDICATION_NAME, MEDICATION_ROUTE, MEDICATION_ROUTE_MAPPED, 
                      MEDICATION_ADMINISTRATION_TS, DW_UPDATE_TS, DW_UPDATE_TS
               FROM MCHS_CUSTOM_DB.SPRUCE.TEMP_SURGICAL_CASE_OR_ADMIN_MEDS;`;
var sql_drp = `DROP TABLE MCHS_CUSTOM_DB.SPRUCE.TEMP_SURGICAL_CASE_OR_ADMIN_MEDS;`;

try {
    var stmt_tmp = snowflake.createStatement ( {sqlText:sql_tmp} );
    stmt_tmp.execute();

    var stmt_del = snowflake.createStatement ( {sqlText:sql_del} );
    stmt_del.execute();

    var stmt_ins = snowflake.createStatement ( {sqlText:sql_ins} );
    stmt_ins.execute();

    var stmt_drp = snowflake.createStatement ( {sqlText:sql_drp} );
    stmt_drp.execute();

    rowCount = stmt_ins.getNumRowsAffected();    
    return "Number of records affected: " + rowCount ;
    }
catch(err) {
           throw "Error Occurred: " + err.message;
           }
$$;


CALL MCHS_CUSTOM_DB.SPRUCE.SP_SURGICAL_CASE_OR_ADMIN_MEDS();
-- Successful 2025.02.10
-- Number of records affected: 171,526 -- for the last 90 days
-- 00:00:09

SELECT COUNT(*) AS COUNT
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS; -- 3,457,790 (most records were loaded manually previously)

