-- MCHS_CUSTOM_DB.SPRUCE.LOAD_AND_SUBMIT.sql
-- RM 2025.02.10 - Creation

--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.LOAD_AND_SUBMIT;
CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.LOAD_AND_SUBMIT (
  SEQ           NUMBER(38,0),
  SP_NAME       VARCHAR(400),
  FILE_NAME     VARCHAR(400),
  EXPORT_FLAG   VARCHAR(1) DEFAULT 'Y',
  EXPORT_SQL    VARCHAR(16777216)
);