-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV
-- RM 2025.01.28 - Creation
-- RM 2025.02.10 - Added missing NCHS_ONLY_SURGICAL_CASE_ID
-- RM 2025.02.11 - Changed GAS_DURATION_MINUTES to minutes since the last measurement


--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,GAS_TS
      ,GAS_DURATION_MINUTES
      ,AIR_VOLUME
      ,O2_VOLUME
      ,N2O_VOLUME
      ,EXPIRED_DES_PERCENT
      ,EXPIRED_ISO_PERCENT
      ,EXPIRED_SEVO_PERCENT
      ,INSPIRED_SEVOFLURANE
      ,CURRENT_TIMESTAMP AS DW_CREATE_TS 
      ,CURRENT_TIMESTAMP AS DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ENV
ORDER BY NCHS_ONLY_SURGICAL_CASE_ID,
         GAS_TS;

-- Successful 2025.02.10
-- Updated Rows    721,334
-- Execute time    00:00:36
-- Start time  Tue Feb 11 14:07:00 EST 2025
-- Finish time Tue Feb 11 14:07:36 EST 2025

SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV
WHERE OR_SURGICAL_CASE_IDENTIFIER = 'MAIN-2024-3835';

