-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS
-- RM 2025.02.05 - Creation
-- RM 2025.02.21 - Recreated with additional columns to track the 30-days after surgery cap.

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_ENCOUNTER_TYPE
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_ENCOUNTER_TS
      ,NCHS_ONLY_SURGERY_START_TS
      ,NCHS_ONLY_DAYS_SINCE_SURGERY
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,ED_ENCOUNTER_IDENTIFIER
      ,ED_ARRIVAL_TS
      ,DW_UPDATE_TS AS DW_CREATE_TS
      ,DW_UPDATE_TS AS DW_UPDATE_TS 
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ED_ARRIVALS
ORDER BY OR_SURGICAL_CASE_IDENTIFIER,
         ED_ARRIVAL_TS;

-- Successful 2025.02.25
-- Updated Rows 1,809 (previously 49K without the cap)
-- Execute time    00:00:01
-- Start time  Tue Feb 25 14:29:14 EST 2025
-- Finish time Tue Feb 25 14:29:16 EST 2025



SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS
ORDER BY OR_SURGICAL_CASE_IDENTIFIER,
         ED_ARRIVAL_TS;