-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE
-- RM 2025.02.03 - Creation


--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE 
SELECT NCHS_ONLY_PERSON_ID 
      ,NCHS_ONLY_MRN 
      ,NCHS_ONLY_ENCOUNTER_ID 
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,CPT_CODE
      ,CPT_DESCRIPTION
      ,DW_UPDATE_TS AS DW_CREATE_TS
      ,DW_UPDATE_TS AS DW_UPDTE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ANES_PROCEDURE 
ORDER BY OR_SURGICAL_CASE_IDENTIFIER
        ,CPT_CODE;

-- Successful 2025.02.10
-- Updated Rows    50,845
-- Execute time    00:00:01
-- Start time  Mon Feb 10 14:01:09 EST 2025
-- Finish time Mon Feb 10 14:01:10 EST 2025