-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ICD.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ICD
-- RM 2025.02.05 - Creation

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ICD;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ICD
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,NCHS_ONLY_DIAGNOSIS_ID
      ,NCHS_ONLY_DIAGNOSIS_PROVIDER_ID
      ,NCHS_ONLY_DIAGNOSIS_PROVIDER
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,ICD10_CODE
      ,ICD10_DESCRIPTION
      ,DW_UPDATE_TS AS DW_CREATE_TS
      ,DW_UPDATE_TS AS DW_UPDATE_TS 
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ICD
ORDER BY OR_SURGICAL_CASE_IDENTIFIER;

-- Successfull 2025.02.10
-- Updated Rows    106,103
-- Execute time    00:00:05
-- Start time  Mon Feb 10 14:31:20 EST 2025
-- Finish time Mon Feb 10 14:31:25 EST 2025