-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
-- RM 2025.01.28 - Creation

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,NCHS_ONLY_PROVIDER_ID          
      ,NCHS_ONLY_ROLE_PERFORMED_CD       
      ,NCHS_ONLY_STAFF_ROLE_PERFORMED 
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,STAFF_NAME
      ,STAFF_ROLE
      ,DW_UPDATE_TS AS DW_CREATE_TS 
      ,DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_STAFF;

-- Successfull     2025.02.10
-- Updated Rows    277,873
-- Execute time    00:00:03
-- Start time  Mon Feb 10 13:41:37 EST 2025
-- Finish time Mon Feb 10 13:41:41 EST 2025

SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
WHERE OR_SURGICAL_CASE_IDENTIFIER = 'MAIN-2024-3835';

SELECT DISTINCT 
       NCHS_ONLY_STAFF_ROLE_PERFORMED
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
WHERE STAFF_ROLE = '<UNKNOWN>'
ORDER BY NCHS_ONLY_STAFF_ROLE_PERFORMED;