-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS
-- RM 2025.02.04 - Creation


--TRUNCATE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS 
SELECT NCHS_ONLY_PERSON_ID 
      ,NCHS_ONLY_MRN 
      ,NCHS_ONLY_ENCOUNTER_ID 
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,NCHS_ONLY_ORDER_ID_SEQUENCE
      ,NCHS_ONLY_ORDER_PROVIDER_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,MEDICATION_NAME
      ,MEDICATION_ROUTE
      ,MEDICATION_ROUTE_MAPPED
      ,MEDICATION_ADMINISTRATION_TS
      ,DW_UPDATE_TS AS DW_CREATE_TS
      ,DW_UPDATE_TS AS DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ADMIN_MEDS 
ORDER BY OR_SURGICAL_CASE_IDENTIFIER
        ,MEDICATION_ADMINISTRATION_TS
        ,MEDICATION_NAME;

-- Successful 2025.02.10
-- Updated Rows    3,457,790
-- Execute time    00:00:11
-- Start time  Mon Feb 10 13:26:51 EST 2025
-- Finish time Mon Feb 10 13:27:03 EST 2025
