-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS
-- RM 2025.02.05 - Creation

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,ED_ENCOUNTER_IDENTIFIER
      ,ED_ARRIVAL_TS
      ,DW_UPDATE_TS AS DW_CREATE_TS
      ,DW_UPDATE_TS AS DW_UPDATE_TS 
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ED_ARRIVALS
ORDER BY OR_SURGICAL_CASE_IDENTIFIER,
         ED_ARRIVAL_TS;

-- Successful 2025.02.07
-- Updated Rows 41,909
-- Execute time 00:00:04
-- Start time  Fri Feb 07 10:00:59 EST 2025
-- Finish time Fri Feb 07 10:01:03 EST 2025
