-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR
-- RM 2025.01.28 - Creation


--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,SURGICAL_CASE_IDENTIFIER
      ,ENCOUNTER_IDENTIFIER
      ,MEDICAL_RECORD_NUMBER
      ,LEGAL_SEX
      ,RACE
      ,ETHNICITY
      ,"LANGUAGE"
      ,ZIP_CODE
      ,HEIGHT_CM
      ,WEIGHT_KG
      ,FACILITY_NAME
      ,PATIENT_AGE_IN_YEARS
      ,PATIENT_AGE_IN_MONTHS
      ,PRIMARY_PAYOR_NAME
      ,PRIMARY_PAYOR_FINANCIAL_CLASS
      ,PATIENT_CLASS
      ,OR_ROOM_NAME
      ,PRIMARY_PROCEDURE_NAME
      ,PROCEDURE_COUNT
      ,CASE_ELECTIVE
      ,SCHEDULED_START_TS
      ,PRIMARY_SURGEON_NAME
      ,SURGICAL_SPECIALTY
      ,WHEELED_INTO_OR_TS
      ,SURGERY_START_TS
      ,SURGICAL_CLOSE_TS
      ,WHEELED_OUT_OF_OR_TS
      ,HOSPITAL_ADMIT_INPATIENT_TS
      ,HOSPITAL_DISCHARGE_TS
      ,ASA_SCORE
      ,AIRWAY_GRADE
      ,ANESTHESIA_START_TS
      ,ANESTHESIA_READY_TS
      ,ANESTHESIA_STOP_TS
      ,PACU_1_ADMIT_TS
      ,PACU_1_DISCHARGE_TS
      ,PACU_2_ADMIT_TS
      ,PACU_2_DISCHARGE_TS
      ,DW_UPDATE_TS AS DW_CREATE_TS 
      ,DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR
WHERE SURGERY_START_TS > '2022-01-01' 
;

-- Successful      2025.02.10
-- Updated Rows    31,133
-- Execute time    00:00:15
-- Start time  Mon Feb 10 13:21:44 EST 2025
-- Finish time Mon Feb 10 13:21:59 EST 2025
