-- DML - MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS.sql
-- Initial population of MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS
-- RM 2025.02.03 - Creation

--TRUNCATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS;
INSERT INTO MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,NCHS_ONLY_ACTION_DT_TM
      ,NCHS_ONLY_SA_ACTION_ID
      ,NCHS_ONLY_EVENT_ID
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,ANESTHESIA_ACTION
      ,DW_UPDATE_TS AS DW_CREATE_TS 
      ,DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ANES_ACTIONS
ORDER BY OR_SURGICAL_CASE_IDENTIFIER,
         NCHS_ONLY_ACTION_DT_TM,
         ANESTHESIA_ACTION;

-- Successful 2025.02.10
-- Updated Rows    2,749,696
-- Execute time    00:00:09
-- Start time  Mon Feb 10 13:52:23 EST 2025
-- Finish time Mon Feb 10 13:52:32 EST 2025
