-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_30D_READMIT.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints


USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_30D_READMIT;

CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_30D_READMIT (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ENCOUNTER_IDENTIFIER                    VARCHAR(400) COMMENT 'Unique patient encounter identifier',
      MEDICAL_RECORD_NUMBER                   VARCHAR(400) COMMENT 'Unique patient identifier',
      PATIENT_ADMITTED_TO_HOSPITAL_TS         TIMESTAMP_LTZ(9) COMMENT 'Patient admitted to the hospital TS',
      HOSPITAL_DISCHARGE_TS                   TIMESTAMP_LTZ(9) COMMENT 'Patient discharged from the hospital TS'
);


ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_30D_READMIT MODIFY (
     COLUMN ENCOUNTER_IDENTIFIER SET NOT NULL,
     COLUMN MEDICAL_RECORD_NUMBER SET NOT NULL);

