-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_RETURN.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints


USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_RETURN;

CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_RETURN (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ENCOUNTER_IDENTIFIER                    VARCHAR(400) COMMENT 'Unique patient encounter identifier',
      MEDICAL_RECORD_NUMBER                   VARCHAR(400) COMMENT 'Unique patient identifier',
      PATIENT_ADMITTED_TO_ED_TS               TIMESTAMP_LTZ(9) COMMENT 'Patient admitted to the ED TS',
      PATIENT_DISCHARGED_FROM_ED_TS           TIMESTAMP_LTZ(9) COMMENT 'Patient discharged from the ED TS'
);


ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_RETURN MODIFY (
     COLUMN ENCOUNTER_IDENTIFIER SET NOT NULL,
     COLUMN MEDICAL_RECORD_NUMBER SET NOT NULL);
