-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PROCEDURE.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints


USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PROCEDURE;

CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PROCEDURE (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ENCOUNTER_IDENTIFIER                    VARCHAR(400) COMMENT 'Unique patient encounter identifier',
      PROCEDURE_CODES                         VARCHAR(400) COMMENT 'Post-discharge CPT codes',
      PROCEDURE_DESCRIPTIONS                  VARCHAR(400) COMMENT 'Post-discharge CPT descriptions'
);


ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PROCEDURE MODIFY (
     COLUMN SURGICAL_CASE_IDENTIFIER SET NOT NULL,
     COLUMN ENCOUNTER_IDENTIFIER SET NOT NULL);
