-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_DIAGNOSIS.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints

USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_DIAGNOSIS;


CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_DIAGNOSIS (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ENCOUNTER_IDENTIFIER                    VARCHAR(400) COMMENT 'Unique patient encounter identifier',
      ICD10_CODES                             VARCHAR(400) COMMENT 'Post-discharge ICD-10 codes',
      ICD10_DESCRIPTIONS                      VARCHAR(400) COMMENT 'Post-discharge ICD-10 descriptions'
);


ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_DIAGNOSIS MODIFY (
     COLUMN SURGICAL_CASE_IDENTIFIER SET NOT NULL,
     COLUMN ENCOUNTER_IDENTIFIER SET NOT NULL);
