-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_ANES_ACTIONS.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints


USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_ANES_ACTIONS;

CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_ANES_ACTIONS (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ANESTHESIA_ACTIONS                      VARCHAR(400) COMMENT 'Actions performed by anesthesiologists (line placements, intubation, etc.)'
);

ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_ANES_ACTIONS MODIFY (
     COLUMN SURGICAL_CASE_IDENTIFIER SET NOT NULL);
