-- MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PAIN.sql
-- RM 2024.09.10 - Creation
-- RM 2024.09.17 - Added NOT NULL constraints


USE DATABASE MCHS_CUSTOM_DB;
--CREATE SCHEMA SPRUCE;
--DROP TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PAIN;


CREATE TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PAIN (
      SURGICAL_CASE_IDENTIFIER                VARCHAR(400) COMMENT 'Unique surgical case identifier',
      ENCOUNTER_IDENTIFIER                    VARCHAR(400) COMMENT 'Unique patient encounter identifier',
      PAIN_SCORE_TS                           TIMESTAMP_LTZ(9) COMMENT 'Pain score is recorded TS',
      PAIN_SCORE                              VARCHAR(400) COMMENT 'Pain score reported by patient, 1-10 scale'
);


ALTER TABLE MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_PAIN MODIFY (
     COLUMN SURGICAL_CASE_IDENTIFIER SET NOT NULL,
     COLUMN ENCOUNTER_IDENTIFIER SET NOT NULL);
