-- MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ANES_ACTIONS.sql
-- RM 2025.02.03 - Creation

CREATE OR REPLACE VIEW MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ANES_ACTIONS AS (
SELECT SCO.NCHS_ONLY_PERSON_ID                    AS NCHS_ONLY_PERSON_ID
      ,SCO.NCHS_ONLY_MRN                          AS NCHS_ONLY_MRN
      ,SCO.NCHS_ONLY_ENCOUNTER_ID                 AS NCHS_ONLY_ENCOUNTER_ID
      ,SCO.NCHS_ONLY_FIN                          AS NCHS_ONLY_FIN
      ,SCO.NCHS_ONLY_SURGICAL_CASE_ID             AS NCHS_ONLY_SURGICAL_CASE_ID
      ,SCA.ACTION_DT_TM                           AS NCHS_ONLY_ACTION_DT_TM 
      ,SCA.SA_ACTION_ID                           AS NCHS_ONLY_SA_ACTION_ID 
      ,SCA.EVENT_ID                               AS NCHS_ONLY_EVENT_ID
      ,SCO.SURGICAL_CASE_IDENTIFIER               AS OR_SURGICAL_CASE_IDENTIFIER
      ,SCO.ENCOUNTER_IDENTIFIER                   AS OR_ENCOUNTER_IDENTIFIER
      ,SCA.SA_ACTION                              AS ANESTHESIA_ACTION
      ,CURRENT_TIMESTAMP                          AS DW_UPDATE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR SCO
JOIN (SELECT SAR.SURGICAL_CASE_ID 
            ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
            ,SAR.SA_ANESTHESIA_RECORD_ID
            ,SA.SA_ACTION_ID
            ,SA.PREV_ACTION_ID 
            ,SA.ACTION_DT_TM 
            ,SRA.SA_REF_ACTION_ID 
            ,CE.EVENT_ID 
            ,CONCAT(SRA.ACTION_NAME, ' - ', CE.SA_ACTION) AS SA_ACTION
      FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
      JOIN MCHS_DB.MCHS_PROD.SA_ACTION                 SA
        ON SAR.SA_ANESTHESIA_RECORD_ID = SA.SA_ANESTHESIA_RECORD_ID 
      JOIN MCHS_DB.MCHS_PROD.SA_REF_ACTION             SRA
        ON SRA.SA_REF_ACTION_ID = SA.SA_REF_ACTION_ID 
      JOIN (SELECT EVENT_ID,
                   T.VALUE AS SA_ACTION   
            FROM MCHS_DB.MCHS_PROD.CLINICAL_EVENT, 
            LATERAL SPLIT_TO_TABLE(RESULT_VAL, CHR(10)) T
            WHERE RESULT_STATUS_CD = 25
              AND RESULT_VAL IS NOT NULL) CE
        ON CE.EVENT_ID = SA.EVENT_ID 
      WHERE SAR.ACTIVE_IND = 1
        AND SAR.ACTIVE_STATUS_CD = 188
        AND SA.ACTIVE_IND = 1
        AND SA.ACTIVE_STATUS_CD = 188
        AND SRA.ACTIVE_IND = 1
        AND SRA.ACTIVE_STATUS_CD = 188) SCA
  ON SCO.NCHS_ONLY_SURGICAL_CASE_ID = SCA.SURGICAL_CASE_ID
ORDER BY SCO.SURGICAL_CASE_IDENTIFIER
        ,SCA.ACTION_DT_TM
        ,SCA.SA_ACTION_ID
);

-- Validation:
--SELECT *
--FROM MCHS_CUSTOM_DB.SPRUCE.VW_SURGICAL_CASE_OR_ANES_ACTIONS
--WHERE OR_SURGICAL_CASE_IDENTIFIER = 'MAIN-2024-3835';  

