SELECT CE.PERSON_ID
      ,CE.ENCNTR_ID
      ,DE.MRN
      ,DE.FIN
      ,CASE 
         WHEN CE.EVENT_CLASS_CD IN (223, 233, 236) AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135 
           THEN 'Ad-hoc Charted Document'
         WHEN CE.EVENT_CLASS_CD = 231 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135 
           THEN 'Common Document'
         WHEN CE.EVENT_CLASS_CD = 226 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 0 AND CE.EVENT_RELTN_CD = 135 
           THEN 'General Lab'
         WHEN CE.EVENT_CLASS_CD = 232 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135
           THEN 'Medication'
         WHEN CE.EVENT_CLASS_CD = 4053628 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135
           THEN 'Med Intake/Output'
         WHEN CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135
           THEN 'Misc Document'
         WHEN CE.EVENT_CLASS_CD = 226 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135 
           THEN 'PowerForm'
         WHEN CE.EVENT_CLASS_CD = 224 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135 
           THEN 'PowerNote'
         WHEN CE.EVENT_CLASS_CD = 4004128 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135
           THEN 'Procedure'
         WHEN CE.EVENT_CLASS_CD = 234 AND CE.EVENT_ID = CE.PARENT_EVENT_ID AND CE.VIEW_LEVEL = 1 AND CE.EVENT_RELTN_CD = 135 
           THEN 'Radiology'
       END AS DOCUMENT_TYPE
      ,CE.CLINICAL_EVENT_ID
      ,CE.RECORD_STATUS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RECORD_STATUS_CD) AS RECORD_STATUS_DISPLAY
      ,CE.EVENT_ID
      ,CE.PARENT_EVENT_ID
      ,CE.VIEW_LEVEL
      ,CE.EVENT_TITLE_TEXT -- Use MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(EVENT_CD) instead 
      ,CE.EVENT_TAG
      ,CE.EVENT_RELTN_CD  
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_RELTN_CD) AS EVENT_RELTN_DISPLAY
      ,CE.EVENT_CLASS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_CLASS_CD) AS EVENT_CLASS_DISPLAY
      ,CE.COLLATING_SEQ -- MDOC SEQUENCE FOR Sections
      ,CE.EVENT_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_CD) AS EVENT_DISPLAY
      ,CE.EVENT_END_DT_TM
      ,CE.RESULT_VAL
      ,CE.RESULT_UNITS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RESULT_UNITS_CD) AS RESULT_UNITS_DISPLAY
      ,CE.RESULT_TIME_UNITS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RESULT_TIME_UNITS_CD) AS RESULT_TIME_UNITS_DISPLAY
      ,CE.TASK_ASSAY_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.TASK_ASSAY_CD) AS TASK_ASSAY_DISPLAY
      ,CE.RESULT_STATUS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RESULT_STATUS_CD) AS RESULT_STATUS_DISPLAY
      ,CE.VERIFIED_DT_TM
      ,CE.VERIFIED_PRSNL_ID
      ,P.NAME_FULL_FORMATTED
FROM MCHS_DB.MCHS_PROD.CLINICAL_EVENT CE
JOIN MCHS_CUSTOM_DB.DIABETES_DB.ENCOUNTERS DE
  ON CE.ENCNTR_ID = DE.ENCOUNTER_ID
LEFT JOIN MCHS_CUSTOM_DB.ODS.VW_PERSON_OK P
  ON CE.VERIFIED_PRSNL_ID = P.PERSON_ID
--WHERE CE.EVENT_RELTN_CD = 135 -- Root Doc
WHERE CE.RESULT_STATUS_CD NOT IN (31, 33) -- In Error, In Progress
  AND CE.VALID_UNTIL_DT_TM >= CURRENT_TIMESTAMP
  AND CE.EVENT_END_DT_TM >= '2022-12-21' AND CE.EVENT_END_DT_TM <= '2022-12-22' 
  AND DE.MRN = 1160517
--  AND CE.VIEW_LEVEL = 1 -- Root Docs can be either 1 or 0.
--  AND CE.PUBLISH_FLAG = 1 -- States whether the item in this record is viewable via "normal" applications 
--                             (e.g., charts, on-line inquiries, etc.). Audit and/or administrative applications 
--                             would be able to view non-publishable results.
ORDER BY CE.PARENT_EVENT_ID, CE.EVENT_ID;
  
SELECT NAME_FULL_FORMATTED
FROM MCHS_DB.MCHS_PROD.PERSON
WHERE PERSON_ID = 3871994


SELECT *
FROM MCHS_DB.MCHS_PROD.CODE_VALUE
WHERE CODE_VALUE = 232
=IF(AND(Q528="GRP",J528=K528,M528=0,O528="R"),"General Lab",
IF(AND(Q528="mdoc",J528=K528,M528=1,O528="R"),"Common Document",
IF(AND(Q528="GRP",J528=K528,M528=1,O528="R"),"PowerForm",
IF(AND(Q528="DOC",J528=K528,M528=1,O528="R"),"PowerNote",
IF(AND(Q528="Radiology",J528=K528,M528=1,O528="R"),"Radiology",
IF(AND(Q528="NUM",J528=K528,M528=1,O528="R"),"Ad-hoc Charted Document",
IF(AND(Q528="TXT",J528=K528,M528=1,O528="R"),"Ad-hoc Charted Document",
IF(AND(Q528="DATE",J528=K528,M528=1,O528="R"),"Ad-hoc Charted Document",
IF(AND(Q528="MED",J528=K528,M528=1,O528="R"),"Medication",
IF(AND(Q528="IO",J528=K528,M528=1,O528="R"),"Med Intake/Output",
IF(AND(Q528="Procedure",J528=K528,M528=1,O528="R"),"Procedure",
IF(AND(J528=K528,M528=1,O528="R"),"Misc Document",
""))))))))))))