-- Incongruencies in OneFL v6.1 Med Admin.sql
-- RM 2025.02.04 - Creation

SELECT PERSONID       AS NCHS_ONLY_PERSON_ID
      ,PATID          AS NCHS_ONLY_MRN
      ,ENCOUNTERID    AS NCHS_ONLY_ENCOUNTER_ID
      ,FIN            AS NCHS_ONLY_FIN
      ,PRESCRIBINGID
--      ,MEDADMIN_PROVIDERID
--      ,MEDADMIN_START_DATE
--      ,MEDADMIN_START_TIME
      ,CONCAT(TO_CHAR(MEDADMIN_START_DATE,'YYYY-MM-DD'), ' ', MEDADMIN_START_TIME)::TIMESTAMP AS MEDADMIN_START_DT_TM
--      ,MEDADMIN_STOP_DATE
--      ,MEDADMIN_STOP_TIME
      ,CONCAT(TO_CHAR(MEDADMIN_STOP_DATE,'YYYY-MM-DD'), ' ', MEDADMIN_STOP_TIME)::TIMESTAMP AS MEDADMIN_STOP_DT_TM
      --      ,MEDADMIN_TYPE
--      ,MEDADMIN_CODE
      ,MEDADMIN_DOSE_ADMIN
      ,MEDADMIN_DOSE_ADMIN_UNIT
      ,MEDADMIN_ROUTE
--      ,MEDADMIN_SOURCE
      ,RAW_MEDADMIN_MED_NAME
--      ,RAW_MEDADMIN_CODE
--      ,RAW_MEDADMIN_DOSE_ADMIN
      ,RAW_MEDADMIN_DOSE_ADMIN_UNIT
--      ,RAW_MEDADMIN_ROUTE AS RAW_MEDADMIN_ROUTE_CD
      ,CV.DISPLAY         AS RAW_MEDADMIN_ROUTE
FROM MCHS_CUSTOM_DB.RESEARCH.ONEFL_MED_ADMIN
JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV
  ON CV.CODE_VALUE = RAW_MEDADMIN_ROUTE
WHERE ENCOUNTERID = 62298688
ORDER BY RAW_MEDADMIN_MED_NAME
        ,MEDADMIN_START_DT_TM;


SELECT ORDER_ID
      ,ORDER_ACTION_ID
      ,ACTION_SEQUENCE
      ,ORDER_STATUS_CD  -- CAN'T BE TRUSTED!!! Doesn't match the ORDER_STATUS_CD in ORDERS. ORDER_ACTION.ORDER_STATUS_CD has 2543 (Completed) but in ORDERS.ORDER_STATUS_CD has both 2543 (Completed) and 2544 (Deleted)
      ,ORDER_DT_TM
      ,ACTION_DT_TM
      ,CURRENT_START_DT_TM
      ,CLINICAL_DISPLAY_LINE
      ,EFFECTIVE_DT_TM
      ,ORDER_DETAIL_DISPLAY_LINE
      ,VALID_DOSE_DT_TM
      ,ACTION_PERSONNEL_ID
      ,EFFECTIVE_DT_TM
      ,DEPT_STATUS_CD    -- CAN'T BE TRUSTED!!! Doesn't match the DEPT_STATUS_CD in ORDERS.ORDER_ACTION.DEPT_STATUS_CD has 9312 (Completed) but in ORDERS.DEPT_STATUS_CD has both 9312 (Completed) and 9313 (Deleted).
      ,CORE_IND
      ,ACTION_TYPE_CD
FROM MCHS_DB.MCHS_PROD.ORDER_ACTION
WHERE ORDER_STATUS_CD = 2543 -- CAN'T BE TRUSTED!!! Doesn't match the ORDER_STATUS_CD in ORDERS. ORDER_ACTION.ORDER_STATUS_CD has 2543 (Completed) but in ORDERS.ORDER_STATUS_CD has both 2543 (Completed) and 2544 (Deleted)
--  AND ORDER_ID IN (2633833573, 2633740811, 2633833571);
  AND ORDER_ID = 2634254995;

SELECT CODE_VALUE
      ,DISPLAY AS ORDER_STATUS
FROM MCHS_DB.MCHS_PROD.CODE_VALUE
WHERE CODE_VALUE IN (2543   -- Completed
                    ,2544
                    ,2550); -- Deleted

SELECT O.ORDER_ID
      ,O.ORDER_STATUS_CD
      ,CV1.DISPLAY AS ORDER_STATUS
      ,O.ORDER_MNEMONIC
      ,O.DEPT_STATUS_CD
      ,CV2.DISPLAY AS DEPT_STATUS
      ,O.*
FROM MCHS_DB.MCHS_PROD.ORDERS O
JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV1
  ON CV1.CODE_VALUE = O.ORDER_STATUS_CD
JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV2
  ON CV2.CODE_VALUE = O.DEPT_STATUS_CD
--WHERE O.ORDER_ID IN (2633833573, 2633740811, 2633833571);
--  WHERE O.ORDER_ID IN (2633788031, 2634022913);
WHERE O.ORDER_ID = 2634254995;


SELECT CODE_VALUE
      ,DISPLAY AS DEPT_STATUS
FROM MCHS_DB.MCHS_PROD.CODE_VALUE
WHERE CODE_VALUE IN (9312   -- Completed
                    ,9313); -- Deleted
                    
                    
SELECT DISTINCT
       MEDADMIN_ROUTE
FROM MCHS_CUSTOM_DB.RESEARCH.ONEFL_MED_ADMIN      
ORDER BY 1
