-- Sample queries for INTERNAL VALIDATION ONLY.sql
-- RM 2025.01.30 - Creation
-- RM 2025.02.10 - Completed, but the last 2 extracts may change.

-- OR
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,SURGICAL_CASE_IDENTIFIER                             AS SURGICAL_CASE_IDENTIFIER
      ,ENCOUNTER_IDENTIFIER                                 AS ENCOUNTER_IDENTIFIER 
      ,MEDICAL_RECORD_NUMBER                                AS MEDICAL_RECORD_NUMBER 
      ,LEGAL_SEX                                            AS LEGAL_SEX 
      ,RACE                                                 AS RACE 
      ,ETHNICITY                                            AS ETHNICITY 
      ,LANGUAGE                                             AS LANGUAGE 
      ,ZIP_CODE                                             AS ZIP_CODE 
      ,HEIGHT_CM                                            AS HEIGHT_CM 
      ,WEIGHT_KG                                            AS WEIGHT_KG 
      ,FACILITY_NAME                                        AS FACILITY_NAME 
      ,PATIENT_AGE_IN_YEARS                                 AS PATIENT_AGE_IN_YEARS 
      ,PATIENT_AGE_IN_MONTHS                                AS PATIENT_AGE_IN_MONTHS 
      ,PRIMARY_PAYOR_NAME                                   AS PRIMARY_PAYOR_NAME 
      ,PRIMARY_PAYOR_FINANCIAL_CLASS                        AS PRIMARY_PAYOR_FINANCIAL_CLASS 
      ,PATIENT_CLASS                                        AS PATIENT_CLASS 
      ,OR_ROOM_NAME                                         AS OR_ROOM_NAME 
      ,PRIMARY_PROCEDURE_NAME                               AS PRIMARY_PROCEDURE_NAME 
      ,PROCEDURE_COUNT                                      AS PROCEDURE_COUNT 
      ,CASE_ELECTIVE                                        AS CASE_ELECTIVE 
      ,SUBSTRING(SCHEDULED_START_TS::STRING,1,19)           AS SCHEDULED_START_TS 
      ,PRIMARY_SURGEON_NAME                                 AS PRIMARY_SURGEON_NAME
      ,SURGICAL_SPECIALTY                                   AS SURGICAL_SPECIALTY
      ,SUBSTRING(WHEELED_INTO_OR_TS::STRING,1,19)           AS WHEELED_INTO_OR_TS 
      ,SUBSTRING(SURGERY_START_TS::STRING,1,19)             AS SURGERY_START_TS
      ,SUBSTRING(SURGICAL_CLOSE_TS::STRING,1,19)            AS SURGICAL_CLOSE_TS
      ,SUBSTRING(WHEELED_OUT_OF_OR_TS::STRING,1,19)         AS WHEELED_OUT_OF_OR_TS
      ,SUBSTRING(HOSPITAL_ADMIT_INPATIENT_TS::STRING,1,19)  AS HOSPITAL_ADMIT_INPATIENT_TS
      ,SUBSTRING(HOSPITAL_DISCHARGE_TS::STRING,1,19)        AS HOSPITAL_DISCHARGE_TS
      ,ASA_SCORE                                            AS ASA_SCORE
      ,AIRWAY_GRADE                                         AS AIRWAY_GRADE
      ,SUBSTRING(ANESTHESIA_START_TS::STRING,1,19)          AS ANESTHESIA_START_TS
      ,SUBSTRING(ANESTHESIA_READY_TS::STRING,1,19)          AS ANESTHESIA_READY_TS
      ,SUBSTRING(ANESTHESIA_STOP_TS::STRING,1,19)           AS ANESTHESIA_STOP_TS
      ,SUBSTRING(PACU_1_ADMIT_TS::STRING,1,19)              AS PACU_1_ADMIT_TS
      ,SUBSTRING(PACU_1_DISCHARGE_TS::STRING,1,19)          AS PACU_1_DISCHARGE_TS
      ,SUBSTRING(PACU_2_ADMIT_TS::STRING,1,19)              AS PACU_2_ADMIT_TS
      ,SUBSTRING(PACU_2_DISCHARGE_TS::STRING,1,19)          AS PACU_2_DISCHARGE_TS
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR
WHERE SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                   'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY NCHS_ONLY_FIN; 


-- OR_ENVIRONMENT
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,OR_SURGICAL_CASE_IDENTIFIER              AS OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER                  AS OR_ENCOUNTER_IDENTIFIER
      ,SUBSTRING(GAS_TS::STRING,1,19)           AS GAS_TS 
      ,GAS_DURATION_MINUTES                     AS GAS_DURATION_MINUTES
      ,AIR_VOLUME                               AS AIR_VOLUME
      ,O2_VOLUME                                AS O2_VOLUME
      ,N2O_VOLUME                               AS N2O_VOLUME
      ,EXPIRED_DES_PERCENT                      AS EXPIRED_DES_PERCENT
      ,EXPIRED_ISO_PERCENT                      AS EXPIRED_ISO_PERCENT
      ,EXPIRED_SEVO_PERCENT                     AS EXPIRED_SEVO_PERCENT 
      ,INSPIRED_SEVOFLURANE                     AS "*** NOT IN SPECS: INSPIRED_SEVOFLURANE *** " 
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ENV
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY NCHS_ONLY_FIN, GAS_TS;


-- STAFF
SELECT NCHS_ONLY_PERSON_ID
      ,NCHS_ONLY_MRN
      ,NCHS_ONLY_ENCOUNTER_ID
      ,NCHS_ONLY_FIN
      ,NCHS_ONLY_SURGICAL_CASE_ID
      ,NCHS_ONLY_PROVIDER_ID
      ,NCHS_ONLY_ROLE_PERFORMED_CD
      ,NCHS_ONLY_STAFF_ROLE_PERFORMED
      ,OR_SURGICAL_CASE_IDENTIFIER
      ,OR_ENCOUNTER_IDENTIFIER
      ,STAFF_NAME
      ,STAFF_ROLE
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY NCHS_ONLY_FIN, STAFF_NAME;


SELECT DISTINCT 
       NCHS_ONLY_STAFF_ROLE_PERFORMED,
       STAFF_ROLE
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
--WHERE STAFF_ROLE IS NULL
ORDER BY NCHS_ONLY_STAFF_ROLE_PERFORMED;


-- ANES_ACTIONS
SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')

-- PROCEDURE
SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY OR_SURGICAL_CASE_IDENTIFIER;              


-- ADMIN MEDS
SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ADMIN_MEDS
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY OR_SURGICAL_CASE_IDENTIFIER
        ,MEDICATION_ADMINISTRATION_TS;

-- ICD
SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ICD
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY OR_SURGICAL_CASE_IDENTIFIER;


-- PAIN
SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_PAIN
WHERE OR_SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                      'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY OR_SURGICAL_CASE_IDENTIFIER
        ,PAIN_SCORE_TS;


-- ED ARRIVALS
-- RM 2025.02.10 - AdaptX current specs don't have a way to tie some of these records to 
--                 a patient, bringing this up on our next meeting with them.
SELECT EDA.*
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ED_ARRIVALS EDA
JOIN MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR SCOR
  ON EDA.NCHS_ONLY_PERSON_ID = SCOR.NCHS_ONLY_PERSON_ID 
WHERE SCOR.SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                        'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY EDA.OR_ENCOUNTER_IDENTIFIER,
         EDA.OR_SURGICAL_CASE_IDENTIFIER;


-- HOSPITAL ADMITS
-- RM 2025.02.10 - AdaptX current specs don't have a way to tie some of these records to 
--                 a patient, bringing this up on our next meeting with them.
SELECT HA.*
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_HOSPITAL_ADMITS HA
JOIN MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR SCOR
  ON HA.NCHS_ONLY_PERSON_ID = SCOR.NCHS_ONLY_PERSON_ID 
WHERE SCOR.SURGICAL_CASE_IDENTIFIER IN ('MAIN-2024-3835', 'MPS-2024-4761', 'MAIN-2024-7948' ,'MPS-2025-3',
                                        'CATH-2024-704' ,'MAIN-2024-8216', 'MAIN-2024-7863' ,'MPS-2024-4510')
ORDER BY HA.OR_ENCOUNTER_IDENTIFIER,
         HA.OR_SURGICAL_CASE_IDENTIFIER;
