-- Surgical Case Header.sql
-- RM 2024.10.28 - Creation

SELECT SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
--      ,WE.PERSON_ID
      ,WE.MEDICAL_RECORD_NUMBER AS MRN
      ,WE.PATIENT
      ,WE.BIRTH_DT_TM::DATE AS DOB
      ,ROUND(DATEDIFF(DAY, WE.BIRTH_DT_TM,COALESCE(WE.REG_DT_TM, WE.INPATIENT_ADMIT_DT_TM, WE.ADMIT_ARRIVE_DATE))/(365.24/12),1) AS AGE_IN_MONTHS
      ,WE.REASON_FOR_VISIT
--      ,WE.ENCOUNTER_ID
      ,WE.FINANCIAL_NUMBER AS FIN
--      ,SAR.SURGICAL_CASE_ID 
--      ,A.SA_ANESTHESIA_RECORD_ID
      ,B.PROC AS PROCEDURES
      ,MAX(CASE WHEN A.CASE_ATTRIBUTE_TYPE_CD = 4056672 THEN CASE_ATTRIBUTE_VALUE END) AS SURGERY_DT_TM
      ,MAX(CASE WHEN A.CASE_ATTRIBUTE_TYPE_CD = 4056669 THEN CASE_ATTRIBUTE_VALUE END) AS PREOP_DIAGNOSIS
      ,MAX(CASE WHEN A.CASE_ATTRIBUTE_TYPE_CD = 4056666 THEN CASE_ATTRIBUTE_VALUE END) AS ASA_CLASS
      ,MAX(CASE WHEN A.CASE_ATTRIBUTE_TYPE_CD = 4056668 THEN CASE_ATTRIBUTE_VALUE END) AS "OR"
      ,MAX(CASE WHEN A.CASE_ATTRIBUTE_TYPE_CD = 4056665 THEN CASE_ATTRIBUTE_VALUE END) AS ANESTHESIA_TYPE
FROM (SELECT SCA.SA_ANESTHESIA_RECORD_ID
            ,SCA.SA_CASE_ATTRIBUTE_ID 
            ,SCA.CASE_ATTRIBUTE_TYPE_CD 
            ,CV1.DISPLAY AS CASE_ATTRIBUTE_TYPE
            ,CASE 
               WHEN SCA.CASE_ATTRIBUTE_TYPE_CD IN (4056665, 4056666, 4056668) 
                 THEN CV2.DISPLAY 
               WHEN SCA.CASE_ATTRIBUTE_TYPE_CD = 4056672 
                 THEN TRY_TO_TIMESTAMP(SCA.CASE_ATTRIBUTE_VALUE_TXT, 'YYYYMMDDHH24MISSFF')::STRING
               ELSE SCA.CASE_ATTRIBUTE_VALUE_TXT
             END AS CASE_ATTRIBUTE_VALUE
      FROM MCHS_DB.MCHS_PROD.SA_CASE_ATTRIBUTE          SCA
      JOIN MCHS_DB.MCHS_PROD.CODE_VALUE                 CV1
        ON CV1.CODE_VALUE = SCA.CASE_ATTRIBUTE_TYPE_CD 
      LEFT JOIN MCHS_DB.MCHS_PROD.CODE_VALUE            CV2
        ON CV2.CODE_VALUE = TRY_TO_NUMBER(SCA.CASE_ATTRIBUTE_VALUE_TXT)
      WHERE SCA.ACTIVE_IND = 1
        AND SCA.ACTIVE_STATUS_CD = 188
        AND SCA.CASE_ATTRIBUTE_TYPE_CD IN (
--                    4056670, -- Procedure
            4056665, -- Anesthesia Type
            4056666, -- ASA Class
            4056668, -- OR
            4056669, -- PreOp Diagnosis
--                    4056671, -- Surgeon
            4056672) -- Surgery DATETIME
      QUALIFY RANK() 
        OVER (PARTITION BY SCA.SA_ANESTHESIA_RECORD_ID, SCA.CASE_ATTRIBUTE_TYPE_CD
              ORDER BY SCA.SA_ANESTHESIA_RECORD_ID, SCA.CASE_ATTRIBUTE_TYPE_CD, 
                       SCA.ACTIVE_STATUS_DT_TM DESC) = 1
      ORDER BY SCA.SA_ANESTHESIA_RECORD_ID
              ,SCA.CASE_ATTRIBUTE_TYPE_CD)        A
JOIN (SELECT P.SA_ANESTHESIA_RECORD_ID 
            ,LISTAGG(P.DISPLAY, '. ') 
             WITHIN GROUP(ORDER BY P.SA_CASE_ATTRIBUTE_ID) AS PROC  
      FROM (SELECT A.SA_ANESTHESIA_RECORD_ID
                  ,A.SA_CASE_ATTRIBUTE_ID
                  ,CV.DISPLAY
            FROM MCHS_DB.MCHS_PROD.SA_CASE_ATTRIBUTE  A
            JOIN MCHS_DB.MCHS_PROD.CODE_VALUE         CV
              ON CV.CODE_VALUE = A.CASE_ATTRIBUTE_VALUE_TXT
            WHERE A.CASE_ATTRIBUTE_TYPE_CD = 4056670 -- Procedure
              AND A.ACTIVE_IND = 1
              AND A.ACTIVE_STATUS_CD = 188
            QUALIFY RANK() OVER (PARTITION BY A.SA_ANESTHESIA_RECORD_ID
                                 ORDER BY A.SA_ANESTHESIA_RECORD_ID, A.ACTIVE_STATUS_DT_TM DESC) = 1
            ORDER BY A.SA_ANESTHESIA_RECORD_ID, A.ACTIVE_STATUS_DT_TM DESC) P
        GROUP BY P.SA_ANESTHESIA_RECORD_ID)       B
  ON A.SA_ANESTHESIA_RECORD_ID = B.SA_ANESTHESIA_RECORD_ID
JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD       SAR
  ON A.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID
JOIN MCHS_DB.MCHS_PROD.SURGICAL_CASE              SC
  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID
JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER         WE
  ON WE.ENCOUNTER_ID = SC.ENCNTR_ID
WHERE SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835' -- SURGICAL_CASE
GROUP BY SAR.RECORD_DESCRIPTION
--        ,WE.PERSON_ID
        ,WE.MEDICAL_RECORD_NUMBER
        ,WE.PATIENT
        ,WE.BIRTH_DT_TM::DATE
        ,ROUND(DATEDIFF(DAY, WE.BIRTH_DT_TM,COALESCE(WE.REG_DT_TM, WE.INPATIENT_ADMIT_DT_TM, WE.ADMIT_ARRIVE_DATE))/(365.24/12),1) 
        ,WE.REASON_FOR_VISIT
--        ,WE.ENCOUNTER_ID
        ,WE.FINANCIAL_NUMBER
--        ,SAR.SURGICAL_CASE_ID 
--        ,A.SA_ANESTHESIA_RECORD_ID
        ,B.PROC;
