-- Surgical Case Medications.sql
-- RM 2024.10.28 - Creation

-- ********** MEDICATION ***************
--    MCHS_DB.MCHS_PROD.SA_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_MEDICATION_ADMIN
--    MCHS_DB.MCHS_PROD.SA_MED_ADMIN_ITEM
--    MCHS_DB.MCHS_PROD.SA_REF_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_REF_CATEGORY 
-- RM 2024.10.01 - Notice that a medication may fall under more than 1 category (i.e. ITEM_ID 1250939, ketorolac 30 mg/mL Inj Sol 1 mL)
-- RM 2024.10.18 - For SF validation:
--                     SAR.RECORD_DESCRIPTION: MAIN-2024-3835
--                     ENCOUNTER_ID: 62298688
--                     PERSON_ID: 8980398
--                 In PowerChart:
--                     Patient: GONZALEZ VENTURINI, LARA
--                     FIN: 1224586638
--                     Search on: 2024.09.12
--                     Notes by: Orihuela Guzman MD  , Giuliana
--                     Form: Anesthesia Printed Record 09/12/2024 16:25 EDT

-- *** TOTALS ***
SELECT WE.PATIENT 
      ,WE.MEDICAL_RECORD_NUMBER AS MRN
      ,WE.FINANCIAL_NUMBER AS FIN
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SC.SURG_START_DT_TM 
      ,MEDS.DRUG_CATEGORIES
      ,MEDS.DRUG_NAME 
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.ADMIN_ROUTE_CD) AS ADMIN_ROUTE
      ,SUM(SMAI.ADMIN_DOSAGE) AS TOTAL_ADMIN_DOSAGE
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD) AS DOSAGE_UNIT
FROM MCHS_DB.MCHS_PROD.SURGICAL_CASE             SC
JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER           WE
  ON WE.ENCOUNTER_ID = SC.ENCNTR_ID 
JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION             SM
  ON SM.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION_ADMIN       SMA
  ON SMA.SA_MEDICATION_ID = SM.SA_MEDICATION_ID
JOIN MCHS_DB.MCHS_PROD.SA_MED_ADMIN_ITEM         SMAI
  ON SMAI.SA_MEDICATION_ADMIN_ID = SMA.SA_MEDICATION_ADMIN_ID 
JOIN (SELECT SRM.ITEM_ID
            ,SRM.SA_REF_MEDICATION_ID
            ,MOIM.DESCRIPTION AS DRUG_NAME
            ,LISTAGG(DISTINCT TRIM(SRC.CATEGORY_NAME), '/') AS DRUG_CATEGORIES
      FROM MCHS_DB.MCHS_PROD.SA_REF_MEDICATION         SRM
      JOIN MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER        MOIM
        ON SRM.ITEM_ID = MOIM.ITEM_MASTER_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION     SRCM
        ON SRCM.SA_REF_MEDICATION_ID = SRM.SA_REF_MEDICATION_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
        ON SRCM.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
      WHERE SRM.ACTIVE_IND = 1
        AND SRM.ACTIVE_STATUS_CD = 188
        AND MOIM.ACTIVE_IND = 1
        AND MOIM.ACTIVE_CD = 188
        AND SRC.ACTIVE_IND = 1
        AND SRC.ACTIVE_STATUS_CD = 188
        AND SRCM.ACTIVE_IND = 1
        AND SRCM.ACTIVE_STATUS_CD = 188
        AND TRIM(MOIM.DESCRIPTION) <> ''  
        AND SRC.SA_REF_CATEGORY_ID <> 271074787 -- All Meds - (removed because it's common to all meds)
      GROUP BY SRM.ITEM_ID
              ,SRM.SA_REF_MEDICATION_ID
              ,MOIM.DESCRIPTION
      ORDER BY MOIM.DESCRIPTION) MEDS
  ON MEDS.SA_REF_MEDICATION_ID = SM.SA_REF_MEDICATION_ID  
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SM.ACTIVE_IND = 1
  AND SM.ACTIVE_STATUS_CD = 188
  AND SMA.ACTIVE_IND = 1
  AND SMA.ACTIVE_STATUS_CD = 188
  AND SMAI.ACTIVE_IND = 1
  AND SMAI.ACTIVE_STATUS_CD = 188
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835'
GROUP BY WE.PATIENT 
        ,WE.MEDICAL_RECORD_NUMBER
        ,WE.FINANCIAL_NUMBER
        ,SAR.RECORD_DESCRIPTION
        ,SC.SURG_START_DT_TM 
        ,MEDS.DRUG_CATEGORIES
        ,MEDS.DRUG_NAME 
        ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.ADMIN_ROUTE_CD)
        ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD)
ORDER BY WE.PATIENT 
        ,WE.MEDICAL_RECORD_NUMBER -- MRN
        ,WE.FINANCIAL_NUMBER      -- FIN
        ,SAR.RECORD_DESCRIPTION   -- SURGICAL_CASE
        ,MEDS.DRUG_NAME;           -- DRUG_NAME


-- *** DETAILS ***
SELECT WE.PATIENT 
      ,WE.MEDICAL_RECORD_NUMBER AS MRN
      ,WE.FINANCIAL_NUMBER AS FIN
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SC.SURG_START_DT_TM 
      ,MEDS.DRUG_CATEGORIES
      ,MEDS.DRUG_NAME 
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.ADMIN_ROUTE_CD) AS ADMIN_ROUTE
--      ,SUM(SMAI.ADMIN_DOSAGE) OVER (PARTITION BY SAR.RECORD_DESCRIPTION, MEDS.DRUG_NAME ORDER BY SAR.RECORD_DESCRIPTION, MEDS.DRUG_NAME) AS TOTAL_ADMIN_DOSAGE
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD) AS DOSAGE_UNIT
      ,SMAI.ADMIN_DOSAGE AS INDIVIDUAL_ADMIN_DOSAGES
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD) AS DOSAGE_UNIT
      ,SMAI.ADMIN_START_DT_TM 
      ,SMAI.ADMIN_STOP_DT_TM 
      ,SMAI.ADMIN_AMOUNT 
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.AMOUNT_UNIT_CD) AS AMOUNT_UNIT
--      ,SMA.ADMIN_RATE_CD
--      ,SMA.CONC_AMOUNT_UNIT_CD -- Concentration Amount Unit Code
--      ,SMA.CONC_DOSAGE         -- Concentration Dosage
--      ,SMA.CONC_AMOUNT         -- Concentration Amount
--      ,SMA.DIR_DOSAGE_UNIT_CD  
--      ,SMA.DIR_TIME_UNIT_CD    
--      ,SMA.WBD_DOSAGE_UNIT_CD  -- WBD (Weight-Based Dosing)
--      ,SMA.WBD_WEIGHT_UNIT_CD  -- WBD (Weight-Based Dosing)
--      ,SMA.WBD_TIME_UNIT_CD    -- WBD (Weight-Based Dosing)
--      ,SMA.PIR_AMOUNT_UNIT_CD  
--      ,SMA.PIR_TIME_UNIT_CD    
--      ,SMA.WEIGHT 
--      ,SMA.WEIGHT_UNIT_CD 
--      ,SMA.HEIGHT 
--      ,SMA.HEIGHT_UNIT_CD 
--      ,SMA.MED_ADMIN_TYPE_FLAG -- 1 = FLUID_ADMIN_TYPE BOLUS,  2 = FLUID_ADMIN_TYPE INFUSION
--      ,SMAI.WEIGHT_BASED_DOSE 
--      ,SMAI.DOSING_INFUSION_RATE 
--      ,SMAI.PUMP_INFUSION_RATE 
--       SC.ENCNTR_ID
--      ,SC.PERSON_ID 
--      ,SAR.SURGICAL_CASE_ID 
--      ,SRC.SA_REF_CATEGORY_ID
--      ,SAR.SA_ANESTHESIA_RECORD_ID
--      ,SRM.ITEM_ID 
--      ,MOIM.ITEM_COUNT 
--      ,MOIM.NDC 
--      ,SMA.EVENT_ID 
--      ,SMA.ORDER_ID 
--      ,SMA.TASK_ID 
--      ,SMA.SA_MACRO_ID 
FROM MCHS_DB.MCHS_PROD.SURGICAL_CASE             SC
JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER           WE
  ON WE.ENCOUNTER_ID = SC.ENCNTR_ID 
JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION             SM
  ON SM.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION_ADMIN       SMA
  ON SMA.SA_MEDICATION_ID = SM.SA_MEDICATION_ID
JOIN MCHS_DB.MCHS_PROD.SA_MED_ADMIN_ITEM         SMAI
  ON SMAI.SA_MEDICATION_ADMIN_ID = SMA.SA_MEDICATION_ADMIN_ID 
JOIN (SELECT SRM.ITEM_ID
            ,SRM.SA_REF_MEDICATION_ID
            ,MOIM.DESCRIPTION AS DRUG_NAME
            ,LISTAGG(DISTINCT TRIM(SRC.CATEGORY_NAME), '/') AS DRUG_CATEGORIES
      FROM MCHS_DB.MCHS_PROD.SA_REF_MEDICATION         SRM
      JOIN MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER        MOIM
        ON SRM.ITEM_ID = MOIM.ITEM_MASTER_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION     SRCM
        ON SRCM.SA_REF_MEDICATION_ID = SRM.SA_REF_MEDICATION_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
        ON SRCM.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
      WHERE SRM.ACTIVE_IND = 1
        AND SRM.ACTIVE_STATUS_CD = 188
        AND MOIM.ACTIVE_IND = 1
        AND MOIM.ACTIVE_CD = 188
        AND SRC.ACTIVE_IND = 1
        AND SRC.ACTIVE_STATUS_CD = 188
        AND SRCM.ACTIVE_IND = 1
        AND SRCM.ACTIVE_STATUS_CD = 188
        AND TRIM(MOIM.DESCRIPTION) <> ''  
        AND SRC.SA_REF_CATEGORY_ID <> 271074787 -- All Meds - (removed because it's common to all meds)
      GROUP BY SRM.ITEM_ID
              ,SRM.SA_REF_MEDICATION_ID
              ,MOIM.DESCRIPTION
      ORDER BY MOIM.DESCRIPTION) MEDS
  ON MEDS.SA_REF_MEDICATION_ID = SM.SA_REF_MEDICATION_ID  
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SM.ACTIVE_IND = 1
  AND SM.ACTIVE_STATUS_CD = 188
  AND SMA.ACTIVE_IND = 1
  AND SMA.ACTIVE_STATUS_CD = 188
  AND SMAI.ACTIVE_IND = 1
  AND SMAI.ACTIVE_STATUS_CD = 188
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835'
ORDER BY WE.PATIENT 
        ,WE.MEDICAL_RECORD_NUMBER -- MRN
        ,WE.FINANCIAL_NUMBER      -- FIN
        ,SAR.RECORD_DESCRIPTION   -- SURGICAL_CASE
        ,MEDS.DRUG_NAME           -- DRUG_NAME
        ,SMAI.ADMIN_START_DT_TM; 


-- CLASSIFICATION
SELECT DISTINCT 
       MEDS.DRUG_CATEGORIES
      ,MEDS.DRUG_NAME 
FROM (SELECT SRM.ITEM_ID
            ,SRM.SA_REF_MEDICATION_ID
            ,MOIM.DESCRIPTION AS DRUG_NAME
            ,LISTAGG(DISTINCT TRIM(SRC.CATEGORY_NAME), '/') AS DRUG_CATEGORIES
      FROM MCHS_DB.MCHS_PROD.SA_REF_MEDICATION         SRM
      JOIN MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER        MOIM
        ON SRM.ITEM_ID = MOIM.ITEM_MASTER_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION     SRCM
        ON SRCM.SA_REF_MEDICATION_ID = SRM.SA_REF_MEDICATION_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
        ON SRCM.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
      WHERE SRM.ACTIVE_IND = 1
        AND SRM.ACTIVE_STATUS_CD = 188
        AND MOIM.ACTIVE_IND = 1
        AND MOIM.ACTIVE_CD = 188
        AND SRC.ACTIVE_IND = 1
        AND SRC.ACTIVE_STATUS_CD = 188
        AND SRCM.ACTIVE_IND = 1
        AND SRCM.ACTIVE_STATUS_CD = 188
        AND TRIM(MOIM.DESCRIPTION) <> ''  
--        AND SRC.SA_REF_CATEGORY_ID <> 271074787 -- All Meds - (removed because it's common to all meds)
      GROUP BY SRM.ITEM_ID
              ,SRM.SA_REF_MEDICATION_ID
              ,MOIM.DESCRIPTION
      ORDER BY MOIM.DESCRIPTION) MEDS
ORDER BY MEDS.DRUG_CATEGORIES
        ,MEDS.DRUG_NAME;
