-- Understanding Surgical Anesthesia.sql
-- RM 2024.09.23 - Creation
--
-- Tickets/Tasks:
--   PRJTASK0115763 - Create Project SPRUCE queries
--   RITM184622     - Cerner/Surginet Tracking Board
--   PRJTASK0123945 - Children's Surgical Verification Registry Query Builds/Validation

SELECT CV.DISPLAY
FROM MCHS_DB.MCHS_PROD.CODE_VALUE CV
WHERE CV.CODE_VALUE = 4056669;

-- ******** SA_CASE_ATTRIBUTE ********
-- RM 224.09.23 - Only gives a small subset of all the atributes of a case,
--                using a mixed record format (1 attribute per row)
-- RM 2024.10.21 - Notice that there are multiple active records in
--                 MCHS_DB.MCHS_PROD.SA_CASE_ATTRIBUTE for the same surgical case.
--                 I had to use a QUALIFY function to get the record with the active 
--                 update.
SELECT SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SAR.SURGICAL_CASE_ID 
      ,SAR.SA_ANESTHESIA_RECORD_ID
      ,SCA_PLUS.SA_CASE_ATTRIBUTE_ID 
      ,SCA_PLUS.ACTIVE_STATUS_DT_TM
      ,SCA_PLUS.CASE_ATTRIBUTE_TYPE_CD 
      ,SCA_PLUS.CASE_ATTRIBUTE_TYPE
      ,SCA_PLUS.CASE_ATTRIBUTE
FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD SAR
JOIN (
      SELECT SCA.SA_ANESTHESIA_RECORD_ID
            ,SCA.SA_CASE_ATTRIBUTE_ID 
            ,SCA.ACTIVE_STATUS_DT_TM
            ,SCA.CASE_ATTRIBUTE_TYPE_CD 
            ,CV1.DISPLAY AS CASE_ATTRIBUTE_TYPE
            ,COALESCE(CV2.DISPLAY, SCA.CASE_ATTRIBUTE_VALUE_TXT) AS CASE_ATTRIBUTE
      FROM MCHS_DB.MCHS_PROD.SA_CASE_ATTRIBUTE SCA
      JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV1
        ON CV1.CODE_VALUE = SCA.CASE_ATTRIBUTE_TYPE_CD 
      LEFT JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV2
        ON CV2.CODE_VALUE = TRY_TO_NUMBER(SCA.CASE_ATTRIBUTE_VALUE_TXT)
      WHERE SCA.ACTIVE_IND = 1
        AND SCA.ACTIVE_STATUS_CD = 188
      QUALIFY RANK() 
        OVER (PARTITION BY SCA.SA_ANESTHESIA_RECORD_ID, SCA.CASE_ATTRIBUTE_TYPE_CD
              ORDER BY SCA.SA_ANESTHESIA_RECORD_ID, SCA.CASE_ATTRIBUTE_TYPE_CD, 
                       SCA.ACTIVE_STATUS_DT_TM DESC) = 1
      ORDER BY SCA.SA_ANESTHESIA_RECORD_ID
              ,SCA.CASE_ATTRIBUTE_TYPE_CD 
              ,SCA.ACTIVE_STATUS_DT_TM DESC
              ) SCA_PLUS
  ON SAR.SA_ANESTHESIA_RECORD_ID = SCA_PLUS.SA_ANESTHESIA_RECORD_ID 
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
--  AND SAR.RECORD_DESCRIPTION = 'MAIN-2022-5623'
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835'
ORDER BY SAR.RECORD_DESCRIPTION
        ,SAR.SURGICAL_CASE_ID 
        ,SAR.SA_ANESTHESIA_RECORD_ID
        ,SCA_PLUS.CASE_ATTRIBUTE_TYPE_CD
        ,SCA_PLUS.SA_CASE_ATTRIBUTE_ID;
  
SELECT PICS.SURGICALCASE_NUM
      ,PICS.ROLE
      ,PICS.STAFF_NAME
FROM MCHS_CUSTOM_DB.PI.VW_OPTUM_PI_CASE_STAFF PICS
WHERE PICS.SURGICALCASE_NUM = 'MAIN-2024-3835'
ORDER BY PICS.ROLE
        ,PICS.STAFF_NAME;

--SELECT *
--FROM MCHS_CUSTOM_DB.PI.WH_CLN_SURGICAL_CASE PISC
--WHERE PISC.SURGICAL_CASE_NBR_FORMATTED = 'MAIN-2024-3835';


--SELECT PISCP.*
--FROM MCHS_CUSTOM_DB.PI.WH_CLN_SURGICAL_CASE     PISC
--JOIN MCHS_CUSTOM_DB.PI.VW_WH_CLN_SURG_CASE_PROC PISCP
--  ON PISC.SURGICAL_CASE_SK = PISCP.SURGICAL_CASE_SK 
--WHERE PISC.SURGICAL_CASE_NBR_FORMATTED = 'MAIN-2024-3835';

  
-- ******** SA_ANESTHESIA_REC_FIELD_VALUES ******** 
-- Empty - Don't use
--SELECT SAR.SA_ANESTHESIA_RECORD_ID 
--      ,SAR.SURGICAL_CASE_ID 
--      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
--      ,SARFV.*
--FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD           SAR
--JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_REC_FIELD_VALUES SARFV
--  ON SAR.SA_ANESTHESIA_RECORD_ID = SARFV.SA_ANESTHESIA_RECORD_ID 
--WHERE SAR.ACTIVE_IND = 1
--  AND SAR.ACTIVE_STATUS_CD = 188
--  AND SARFV.ACTIVE_IND = 1
--  AND SARFV.ACTIVE_STATUS_CD = 188
--  AND SAR.SURGICAL_CASE_ID = 631469764;
--
--  
--SELECT DISTINCT 
--       SCP.ANESTHESIA_TYPE_REF
--      ,CV.DISPLAY AS ANESTHESIA_TYPE
--FROM MCHS_CUSTOM_DB.PI.VW_WH_CLN_SURG_CASE_PROC SCP
--JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV
--  ON CV.CODE_VALUE = SCP.ANESTHESIA_TYPE_REF 
--ORDER BY 2;  


-- ******* SA_ANESTHESIA_RECORD and CLINICAL_EVENT *******
-- RM 2024.09.23 - The following query only resturns a "Finalized" "Anesthesia Record",
--                 but none of the anesthesia actions taken within a surgical case.
--                 Also notice that the CODE_VALUEs are inactive!
-- Don't use
--SELECT SAR.SURGICAL_CASE_ID 
--      ,SAR.RECORD_DESCRIPTION 
--      ,CE.EVENT_ID 
--      ,CE.EVENT_END_DT_TM 
--      ,CE.EVENT_CD 
--      ,CV.DISPLAY AS EVENT
--      ,CE.EVENT_TAG 
--FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD SAR
--JOIN MCHS_DB.MCHS_PROD.CLINICAL_EVENT CE
--  ON CE.EVENT_ID = SAR.EVENT_ID 
--JOIN MCHS_DB.MCHS_PROD.CODE_VALUE CV
--  ON CV.CODE_VALUE = CE.EVENT_CD 
--WHERE SAR.ACTIVE_IND = 1
--  AND SAR.ACTIVE_STATUS_CD = 188
--  AND CE.RESULT_STATUS_CD = 25
----  AND CV.ACTIVE_IND = 1 -- No records will return if the comment is removed.
--  AND SAR.CREATE_DT_TM::DATE  >= '2024-09-21'
--  

-- ******* SA_ANESTHESIA_RECORD, SA_REF_ACTION, SA_ACTION and CLINICAL_EVENT *******
-- Notice that CLINICAL_EVENT.RESULT_VAL is a concat of observations (Questions and Responses) 
-- Notice that SA_ACTION_ITEM and SA_REF_ACTION_ITEM provide partial, unspecified answers. Use CLINICAL_EVENT.RESULT_VAL instead. 
-- Some CLINICAL_EVENT.RESULT_VAL are NULL (timstamps, already captured elsewhere), and so are filtered out.  
SELECT SAR.SURGICAL_CASE_ID 
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SAR.SA_ANESTHESIA_RECORD_ID
      ,SA.SA_ACTION_ID
      ,SA.PREV_ACTION_ID 
      ,SA.ACTION_DT_TM 
      ,SRA.SA_REF_ACTION_ID 
      ,SRA.ACTION_NAME 
      ,CE.EVENT_ID 
      ,CE.RESULT_VAL
--      ,SAI.ACTION_VALUE 
--      ,SAI.SA_REF_ACTION_ITEM_ID 
--      ,SRAI.ACTION_ITEM_NAME 
FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
JOIN MCHS_DB.MCHS_PROD.SA_ACTION                 SA
  ON SAR.SA_ANESTHESIA_RECORD_ID = SA.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_REF_ACTION             SRA
  ON SRA.SA_REF_ACTION_ID = SA.SA_REF_ACTION_ID 
JOIN MCHS_DB.MCHS_PROD.CLINICAL_EVENT            CE
  ON CE.EVENT_ID = SA.EVENT_ID 
--JOIN MCHS_DB.MCHS_PROD.SA_ACTION_ITEM            SAI
--  ON SAI.SA_ACTION_ID = SA.SA_ACTION_ID 
--JOIN MCHS_DB.MCHS_PROD.SA_REF_ACTION_ITEM        SRAI
--  ON SRAI.SA_REF_ACTION_ITEM_ID = SAI.SA_REF_ACTION_ITEM_ID 
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SA.ACTIVE_IND = 1
  AND SA.ACTIVE_STATUS_CD = 188
  AND SRA.ACTIVE_IND = 1
  AND SRA.ACTIVE_STATUS_CD = 188
  AND CE.RESULT_STATUS_CD = 25
  AND CE.RESULT_VAL IS NOT NULL 
  AND SAR.SURGICAL_CASE_ID = 616035619
--  AND SAI.ACTIVE_IND = 1
--  AND SAI.ACTIVE_STATUS_CD = 188
--  AND SRAI.ACTIVE_IND = 1
--  AND SRAI.ACTIVE_STATUS_CD = 188
ORDER BY SAR.SURGICAL_CASE_ID
        ,SA.ACTION_DT_TM
        ,SA.SA_ACTION_ID;

        
SELECT *
FROM MCHS_DB.MCHS_PROD.SA_REF_ACTION_ITEM        SRAI
WHERE SA_REF_ACTION_ITEM_ID = 1890713223;

SELECT *
FROM MCHS_DB.MCHS_PROD.DISCRETE_TASK_ASSAY 
WHERE TASK_ASSAY_CD = 69558234;

SELECT DISPLAY
FROM MCHS_DB.MCHS_PROD.CODE_VALUE 
WHERE CODE_VALUE = 69558231;

-- The following tables are not used - they contain less than 5 records each, added during migration. They require to tie to ITEM_MASTER
-- MCHS_DB.MCHS_PROD.SA_ITEM
-- MCHS_DB.MCHS_PROD.SA_ITEM_USAGE
-- SA_REF_ITEM - Currently does not exist in SF - it is not crawled into MCHS_DB.MCHS_PROD as it is almost empty in V500


-- ******* SA_ANESTHESIA_RECORD, SA_MACRO, SA_REF_MACRO, SA_REF_CATEGORY *******
-- SA_REF_CATEGORY doesn't add much information, as it points back to Anesthesia
SELECT SAR.SURGICAL_CASE_ID 
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SAR.SA_ANESTHESIA_RECORD_ID
      ,SM.SA_MACRO_ID
      ,SM.EXECUTE_DT_TM
      ,SM.SA_REF_MACRO_ID 
      ,SRM.MACRO_NAME 
      ,SRM.SA_REF_CATEGORY_ID 
--      ,SRC.CATEGORY_NAME 
FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
JOIN MCHS_DB.MCHS_PROD.SA_MACRO                  SM
  ON SAR.SA_ANESTHESIA_RECORD_ID = SM.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_CUSTOM_DB.STG_V500.SA_REF_MACRO        SRM
  ON SRM.SA_REF_MACRO_ID = SM.SA_REF_MACRO_ID 
--JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
--  ON SRM.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SM.ACTIVE_IND = 1
  AND SM.ACTIVE_STATUS_CD = 188
  AND SRM.ACTIVE_IND = 1
  AND SRM.ACTIVE_STATUS_CD = 188
  AND SAR.SURGICAL_CASE_ID = 631469764;
--  AND SRC.ACTIVE_IND = 1
--  AND SRC.ACTIVE_STATUS_CD = 188

-- TODO: continue adding all SA_MACRO children:
--    MCHS_DB.MCHS_PROD.SA_ACTION
--    MCHS_DB.MCHS_PROD.SA_ACTION_ITEM
--    MCHS_DB.MCHS_PROD.SA_REF_ACTION  
--  
  
-- ********** FLUIDS (IN/OUT) ***************  
--    MCHS_DB.MCHS_PROD.SA_FLUID
--    MCHS_DB.MCHS_PROD.SA_FLUID_ADMIN
--    MCHS_DB.MCHS_PROD.SA_REF_FLUID
--    MCHS_DB.MCHS_PROD.SA_FLUID_ADMIN
--    MCHS_DB.MCHS_PROD.SA_REF_CAT_FLUID
--    MCHS_DB.MCHS_PROD.SA_REF_CATEGORY  
SELECT SAR.SURGICAL_CASE_ID 
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SAR.SA_ANESTHESIA_RECORD_ID
      ,SF.SA_FLUID_ID 
      ,SF.SA_MACRO_ID 
      ,SRF.SA_REF_FLUID_ID 
--      ,SRF.TASK_ASSAY_CD 
      ,SRF.ITEM_ID 
      ,SRF.MED_PRODUCT_ID 
      ,MOIM.TYPE_CD 
      ,CV2.DISPLAY AS ITEM_TYPE
      ,SRC.CATEGORY_NAME 
--      ,MOIM.BASE_PKG_DESC 
--      ,MOIM.BASE_PKG_QTY 
--      ,MOIM.CLASS_NAME 
      ,MOIM.DESCRIPTION 
      ,SRF.OUT_IND 
      ,MOIM.ITEM_COUNT 
      ,SRF.EVENT_CD 
      ,CV1.DISPLAY AS EVENT
      ,SFA.WEIGHT 
      ,SFA.WEIGHT_UNIT_CD 
      ,SFA.HEIGHT 
      ,SFA.HEIGHT_UNIT_CD 
      ,SFA.ADMIN_DOSAGE 
      ,SFA.DOSAGE_UNIT_CD 
      ,SFA.ADMIN_AMOUNT 
      ,SFA.AMOUNT_UNIT_CD 
      ,SFA.ADMIN_ROUTE_CD
      ,SFA.ADMIN_SITE_CD 
      ,SFA.ADMIN_RATE_CD 
      ,SFA.ADMIN_START_DT_TM 
      ,SFA.ADMIN_STOP_DT_TM 
      ,SFA.ORDER_ID 
      ,SFA.TASK_ID 
--      ,MOIM.NDC 
FROM MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
JOIN MCHS_DB.MCHS_PROD.SA_FLUID                  SF
  ON SAR.SA_ANESTHESIA_RECORD_ID = SF.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_REF_FLUID              SRF
  ON SRF.SA_REF_FLUID_ID = SF.SA_REF_FLUID_ID 
JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_FLUID          SRCF
  ON SRCF.SA_REF_FLUID_ID = SRF.SA_REF_FLUID_ID
JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
  ON SRCF.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
JOIN MCHS_DB.MCHS_PROD.SA_FLUID_ADMIN            SFA
  ON SFA.SA_FLUID_ID = SF.SA_FLUID_ID 
JOIN MCHS_DB.MCHS_PROD.CODE_VALUE                CV1
  ON CV1.CODE_VALUE = SRF.EVENT_CD
LEFT JOIN MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER   MOIM
  ON SRF.ITEM_ID = MOIM.ITEM_MASTER_ID
LEFT JOIN MCHS_DB.MCHS_PROD.CODE_VALUE           CV2
  ON CV2.CODE_VALUE = MOIM.TYPE_CD 
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SF.ACTIVE_IND = 1
  AND SF.ACTIVE_STATUS_CD = 188
  AND SRF.ACTIVE_IND = 1
  AND SRF.ACTIVE_STATUS_CD = 188
  AND MOIM.ACTIVE_IND = 1
  AND MOIM.ACTIVE_CD = 188
  AND SRCF.ACTIVE_IND = 1
  AND SRCF.ACTIVE_STATUS_CD = 188
  AND SRC.ACTIVE_IND = 1
  AND SRC.ACTIVE_STATUS_CD = 188
  AND SFA.ACTIVE_IND = 1
  AND SFA.ACTIVE_STATUS_CD = 188
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835';
  
--SELECT *
--FROM MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER
--WHERE ITEM_MASTER_ID IN (15337946,1308250,1261697);

--SELECT *
--FROM MCHS_DB.MCHS_PROD.CODE_VALUE 
--WHERE CODE_VALUE = 19604424; -- EBL (Estimated Blood Loss)


-- ********** MEDICATION ***************
--    MCHS_DB.MCHS_PROD.SA_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_MEDICATION_ADMIN
--    MCHS_DB.MCHS_PROD.SA_MED_ADMIN_ITEM
--    MCHS_DB.MCHS_PROD.SA_REF_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION
--    MCHS_DB.MCHS_PROD.SA_REF_CATEGORY 
-- RM 2024.10.01 - Notice that a medication may fall under more than 1 category (i.e. ITEM_ID 1250939, ketorolac 30 mg/mL Inj Sol 1 mL)
-- RM 2024.10.18 - For SF validation:
--                     SAR.RECORD_DESCRIPTION: MAIN-2024-3835
--                     ENCOUNTER_ID: 62298688
--                     PERSON_ID: 8980398
--                 In PowerChart:
--                     Patient: GONZALEZ VENTURINI, LARA
--                     FIN: 1224586638
--                     Search on: 2024.09.12
--                     Notes by: Orihuela Guzman MD  , Giuliana
--                     Form: Anesthesia Printed Record 09/12/2024 16:25 EDT
SELECT WE.PATIENT 
      ,WE.MEDICAL_RECORD_NUMBER AS MRN
      ,WE.FINANCIAL_NUMBER AS FIN
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SC.SURG_START_DT_TM 
      ,MEDS.DRUG_CATEGORIES
      ,MEDS.DRUG_NAME 
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.ADMIN_ROUTE_CD) AS ADMIN_ROUTE
      ,SUM(SMAI.ADMIN_DOSAGE) OVER (PARTITION BY SAR.RECORD_DESCRIPTION, MEDS.DRUG_NAME ORDER BY SAR.RECORD_DESCRIPTION, MEDS.DRUG_NAME) AS TOTAL_ADMIN_DOSAGE
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD) AS DOSAGE_UNIT
      ,SMAI.ADMIN_DOSAGE AS INDIVIDUAL_ADMIN_DOSAGES
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.DOSAGE_UNIT_CD) AS DOSAGE_UNIT
      ,SMAI.ADMIN_START_DT_TM 
      ,SMAI.ADMIN_STOP_DT_TM 
      ,SMAI.ADMIN_AMOUNT 
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(SMA.AMOUNT_UNIT_CD) AS AMOUNT_UNIT
--      ,SMA.ADMIN_RATE_CD
--      ,SMA.CONC_AMOUNT_UNIT_CD -- Concentration Amount Unit Code
--      ,SMA.CONC_DOSAGE         -- Concentration Dosage
--      ,SMA.CONC_AMOUNT         -- Concentration Amount
--      ,SMA.DIR_DOSAGE_UNIT_CD  
--      ,SMA.DIR_TIME_UNIT_CD    
--      ,SMA.WBD_DOSAGE_UNIT_CD  -- WBD (Weight-Based Dosing)
--      ,SMA.WBD_WEIGHT_UNIT_CD  -- WBD (Weight-Based Dosing)
--      ,SMA.WBD_TIME_UNIT_CD    -- WBD (Weight-Based Dosing)
--      ,SMA.PIR_AMOUNT_UNIT_CD  
--      ,SMA.PIR_TIME_UNIT_CD    
--      ,SMA.WEIGHT 
--      ,SMA.WEIGHT_UNIT_CD 
--      ,SMA.HEIGHT 
--      ,SMA.HEIGHT_UNIT_CD 
--      ,SMA.MED_ADMIN_TYPE_FLAG -- 1 = FLUID_ADMIN_TYPE BOLUS,  2 = FLUID_ADMIN_TYPE INFUSION
--      ,SMAI.WEIGHT_BASED_DOSE 
--      ,SMAI.DOSING_INFUSION_RATE 
--      ,SMAI.PUMP_INFUSION_RATE 
--       SC.ENCNTR_ID
--      ,SC.PERSON_ID 
--      ,SAR.SURGICAL_CASE_ID 
--      ,SRC.SA_REF_CATEGORY_ID
--      ,SAR.SA_ANESTHESIA_RECORD_ID
--      ,SRM.ITEM_ID 
--      ,MOIM.ITEM_COUNT 
--      ,MOIM.NDC 
--      ,SMA.EVENT_ID 
--      ,SMA.ORDER_ID 
--      ,SMA.TASK_ID 
--      ,SMA.SA_MACRO_ID 
FROM MCHS_DB.MCHS_PROD.SURGICAL_CASE             SC
JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER           WE
  ON WE.ENCOUNTER_ID = SC.ENCNTR_ID 
JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION             SM
  ON SM.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_MEDICATION_ADMIN       SMA
  ON SMA.SA_MEDICATION_ID = SM.SA_MEDICATION_ID
JOIN MCHS_DB.MCHS_PROD.SA_MED_ADMIN_ITEM         SMAI
  ON SMAI.SA_MEDICATION_ADMIN_ID = SMA.SA_MEDICATION_ADMIN_ID 
JOIN (SELECT SRM.ITEM_ID
            ,SRM.SA_REF_MEDICATION_ID
            ,MOIM.DESCRIPTION AS DRUG_NAME
            ,LISTAGG(DISTINCT TRIM(SRC.CATEGORY_NAME), '/') AS DRUG_CATEGORIES
      FROM MCHS_DB.MCHS_PROD.SA_REF_MEDICATION         SRM
      JOIN MCHS_DB.MCHS_PROD.MM_OMF_ITEM_MASTER        MOIM
        ON SRM.ITEM_ID = MOIM.ITEM_MASTER_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_MEDICATION     SRCM
        ON SRCM.SA_REF_MEDICATION_ID = SRM.SA_REF_MEDICATION_ID
      JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC
        ON SRCM.SA_REF_CATEGORY_ID = SRC.SA_REF_CATEGORY_ID 
      WHERE SRM.ACTIVE_IND = 1
        AND SRM.ACTIVE_STATUS_CD = 188
        AND MOIM.ACTIVE_IND = 1
        AND MOIM.ACTIVE_CD = 188
        AND SRC.ACTIVE_IND = 1
        AND SRC.ACTIVE_STATUS_CD = 188
        AND SRCM.ACTIVE_IND = 1
        AND SRCM.ACTIVE_STATUS_CD = 188
        AND TRIM(MOIM.DESCRIPTION) <> ''  
        AND SRC.SA_REF_CATEGORY_ID <> 271074787 -- All Meds - (removed because it's common to all meds)
      GROUP BY SRM.ITEM_ID
              ,SRM.SA_REF_MEDICATION_ID
              ,MOIM.DESCRIPTION
      ORDER BY MOIM.DESCRIPTION) MEDS
  ON MEDS.SA_REF_MEDICATION_ID = SM.SA_REF_MEDICATION_ID  
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SM.ACTIVE_IND = 1
  AND SM.ACTIVE_STATUS_CD = 188
  AND SMA.ACTIVE_IND = 1
  AND SMA.ACTIVE_STATUS_CD = 188
  AND SMAI.ACTIVE_IND = 1
  AND SMAI.ACTIVE_STATUS_CD = 188
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835'
ORDER BY WE.PATIENT 
        ,WE.MEDICAL_RECORD_NUMBER -- MRN
        ,WE.FINANCIAL_NUMBER      -- FIN
        ,SAR.RECORD_DESCRIPTION   -- SURGICAL_CASE
        ,MEDS.DRUG_NAME           -- DRUG_NAME;
        ,SMAI.ADMIN_START_DT_TM; 



-- ********** MONITOR (GASES) ***************
--    MCHS_DB.MCHS_PROD.SA_PARAMETER
--    MCHS_DB.MCHS_PROD.SA_PARAMETER_MONITOR
--    MCHS_DB.MCHS_PROD.SA_PARAMETER_VALUE
--    MCHS_DB.MCHS_PROD.SA_REF_PARAMETER
--    MCHS_DB.MCHS_PROD.SA_REF_CAT_PARAMETER -- Not used - all records have the category of 'All Parameters'
--    MCHS_DB.MCHS_PROD.SA_REF_CATEGORY      -- Not used - all records have the category of 'All Parameters'
-- RM 2024.10.01 - Check why only 3 of the 7 task codes are returnng in the query
SELECT SC.ENCNTR_ID
      ,SC.PERSON_ID 
      ,WE.PATIENT 
      ,SC.SURG_START_DT_TM 
      ,SAR.SURGICAL_CASE_ID 
      ,SAR.RECORD_DESCRIPTION AS SURGICAL_CASE
      ,SAR.SA_ANESTHESIA_RECORD_ID
      ,SRP.TASK_ASSAY_CD 
      ,DTA.DESCRIPTION AS TASK_ASSAY
--      ,SRC.CATEGORY_NAME -- Not used - all records have the category of 'All Parameters'
      ,SPV.VALUE_DT_TM
--      ,SPM.*
      ,SPV.NOMENCLATURE_ID 
--      ,SPV.NUMERIC_VALUE - Same as CE.RESULT_VAL
      ,SPV.MONITORED_VALUE_IND 
      ,CE.EVENT_ID 
      ,CE.EVENT_CD 
      ,CE.RESULT_VAL 
--      ,CE.RESULT_UNITS_CD 
      ,CV.DISPLAY AS RESULT_UNITS
      ,CE.EVENT_TAG 
FROM MCHS_DB.MCHS_PROD.SURGICAL_CASE             SC
JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER           WE
  ON WE.ENCOUNTER_ID = SC.ENCNTR_ID 
JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD      SAR
  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID 
JOIN MCHS_DB.MCHS_PROD.SA_PARAMETER              SP
  ON SP.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID 
JOIN MCHS_DB.MCHS_PROD.SA_REF_PARAMETER          SRP
  ON SRP.SA_REF_PARAMETER_ID = SP.SA_REF_PARAMETER_ID
--JOIN MCHS_DB.MCHS_PROD.SA_REF_CAT_PARAMETER      SRCP  -- Not used - all records have the category of 'All Parameters'
--  ON SRCP.SA_REF_PARAMETER_ID = SRP.SA_REF_PARAMETER_ID 
--JOIN MCHS_DB.MCHS_PROD.SA_REF_CATEGORY           SRC  -- Not used - all records have the category of 'All Parameters'
--  ON SRC.SA_REF_CATEGORY_ID = SRCP.SA_REF_CATEGORY_ID 
JOIN MCHS_DB.MCHS_PROD.SA_PARAMETER_MONITOR      SPM
  ON SPM.SA_PARAMETER_ID = SP.SA_PARAMETER_ID 
JOIN MCHS_DB.MCHS_PROD.SA_PARAMETER_VALUE        SPV
  ON SPV.SA_PARAMETER_ID = SP.SA_PARAMETER_ID 
JOIN MCHS_DB.MCHS_PROD.DISCRETE_TASK_ASSAY       DTA
  ON DTA.TASK_ASSAY_CD = SRP.TASK_ASSAY_CD 
JOIN MCHS_DB.MCHS_PROD.CLINICAL_EVENT            CE
  ON CE.EVENT_ID = SPV.EVENT_ID
JOIN MCHS_DB.MCHS_PROD.CODE_VALUE                CV
  ON CV.CODE_VALUE = CE.RESULT_UNITS_CD 
WHERE SAR.ACTIVE_IND = 1
  AND SAR.ACTIVE_STATUS_CD = 188
  AND SP.ACTIVE_IND = 1
  AND SP.ACTIVE_STATUS_CD = 188
  AND SRP.ACTIVE_IND = 1
  AND SRP.ACTIVE_STATUS_CD = 188
--  AND SRCP.ACTIVE_IND = 1
--  AND SRCP.ACTIVE_STATUS_CD = 188
--  AND SRC.ACTIVE_IND = 1
--  AND SRC.ACTIVE_STATUS_CD = 188
  AND SPM.ACTIVE_IND = 1
  AND SPM.ACTIVE_STATUS_CD = 188
  AND SPV.ACTIVE_IND = 1
  AND SPV.ACTIVE_STATUS_CD = 188
  AND CE.RESULT_STATUS_CD = 25
  AND SRP.TASK_ASSAY_CD IN 
         (7230133503, -- Total Gas Flow
          7230129605, -- Fresh Gas Air
          7230133445, -- Fresh Gas O2
          7230559537, -- Fresh Gas N2O
            19818228, -- Expired Desflurane Anes
            19818235, -- Expired Isoflurane Anes
            19818260) -- Expired Sevoflurane Anes
  AND SAR.RECORD_DESCRIPTION = 'MAIN-2024-3835'
ORDER BY SAR.SURGICAL_CASE_ID
        ,DTA.DESCRIPTION
        ,SPV.VALUE_DT_TM;
  
--SELECT DISTINCT 
--       DTA.TASK_ASSAY_CD
--      ,DTA.DESCRIPTION AS TASK_ASSAY
--FROM MCHS_DB.MCHS_PROD.SA_REF_PARAMETER          SRP
--JOIN MCHS_DB.MCHS_PROD.DISCRETE_TASK_ASSAY       DTA
--  ON DTA.TASK_ASSAY_CD = SRP.TASK_ASSAY_CD 
--WHERE SRP.ACTIVE_IND = 1
--  AND SRP.ACTIVE_STATUS_CD = 188
--  AND DTA.ACTIVE_IND = 1
--  AND DTA.ACTIVE_STATUS_CD = 188
--ORDER BY DTA.DESCRIPTION ;

--SELECT WE.FINANCIAL_NUMBER 
--FROM MCHS_CUSTOM_DB.PI.WH_CLN_SURGICAL_CASE SC
--JOIN MCHS_CUSTOM_DB.ODS.VW_W_ENCOUNTER WE
--  ON SC.ENCOUNTER_SK = WE.ENCOUNTER_ID 
--WHERE SURGICAL_CASE_NBR_FORMATTED = 'MAIN-2024-3835'

--SELECT *
--FROM MCHS_DB.MCHS_PROD.DISCRETE_TASK_ASSAY DTA
--WHERE UPPER(DTA.DESCRIPTION) LIKE '%EXPIRED%';

SELECT TO_TIMESTAMP('20240912140100', 'YYYYMMDDHH24MISS')

-- ********** OR (AIRWAY GRADE ) ***************
--    MCHS_DB.MCHS_PROD.CLINIAL_EVENT
-- RM 2025.01.20 - Not available. Several airway events are captured, but not the Airway Grade (Cormack–Lehane classification)
SELECT CE.PERSON_ID
      ,CE.ENCNTR_ID
      ,CE.CLINICAL_EVENT_ID
      ,CE.RECORD_STATUS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RECORD_STATUS_CD) AS RECORD_STATUS
      ,CE.ORDER_ID
      ,CE.EVENT_ID
      ,CE.PARENT_EVENT_ID
      ,CE.EVENT_CLASS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_CLASS_CD) AS EVENT_CLASS
      ,CE.EVENT_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_CD) AS EVENT
      ,CE.EVENT_TITLE_TEXT
      ,CE.TASK_ASSAY_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.TASK_ASSAY_CD) AS TASK_ASSAY
      ,CE.ACCESSION_NBR
      ,CE.CATALOG_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.CATALOG_CD) AS CATALOG_ITEM
      ,CE.CONTRIBUTOR_SYSTEM_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.CONTRIBUTOR_SYSTEM_CD) AS CONTRIBUTOR_SYSTEM
      ,CE.EVENT_RELTN_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.EVENT_RELTN_CD) AS EVENT_RELTN
      ,CE.PUBLISH_FLAG
      ,CE.EVENT_END_DT_TM
      ,CE.RESULT_VAL
      ,CE.EVENT_TAG
      ,CE.RESULT_UNITS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RESULT_UNITS_CD) AS UNITS
      ,CE.RESULT_STATUS_CD
      ,MCHS_CUSTOM_DB.PUBLIC.LOOKUP_DISPLAY(CE.RESULT_STATUS_CD) AS RESULT_STATUS
      ,CE.VERIFIED_DT_TM
      ,CE.VERIFIED_PRSNL_ID
FROM MCHS_DB.MCHS_PROD.CLINICAL_EVENT CE
WHERE CE.RESULT_STATUS_CD = 25
  AND CE.PUBLISH_FLAG = 1
--  AND CE.ENCNTR_ID = 62298688
  AND CE.ENCNTR_ID = 63898914
--  AND CE.EVENT_END_DT_TM::DATE = '2025-01-03'
  AND CE.EVENT_CD IN (SELECT CV.CODE_VALUE FROM MCHS_DB.MCHS_PROD.CODE_VALUE CV WHERE UPPER(CV.DISPLAY) LIKE '%AIRWAY%' AND CV.CODE_SET = 72)
ORDER BY 4;



--SELECT SAC.*
--FROM MCHS_DB.MCHS_PROD.SURGICAL_CASE SC
--JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_RECORD SAR
--  ON SC.SURG_CASE_ID = SAR.SURGICAL_CASE_ID 
--JOIN MCHS_DB.MCHS_PROD.SA_ANESTHESIA_CHARGE SAC
--  ON SAC.SA_ANESTHESIA_RECORD_ID = SAR.SA_ANESTHESIA_RECORD_ID
--WHERE SC.ENCNTR_ID = 62298688;
  
--SELECT *
--FROM MCHS_CUSTOM_DB.ODS.CDS_F_CHARGE
--WHERE FINANCIAL_NUMBER = '1224586638';