-- MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_ANES_ACTIONS.sql
-- RM 2025.02.03 - Creation

ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

-- ANES_ACTIONS
CREATE OR REPLACE VIEW MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_ANES_ACTIONS AS (
SELECT OR_SURGICAL_CASE_IDENTIFIER    AS "or_surgical_case_identifier"
      ,OR_ENCOUNTER_IDENTIFIER        AS "encounter_identifier"
      ,ANESTHESIA_ACTION              AS "anesthesia_action"
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_ACTIONS
);

SELECT *
FROM MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_ANES_ACTIONS
WHERE "or_surgical_case_identifier" = 'MAIN-2024-3835';

