-- MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PROCEDURE.sql
-- RM 2025.02.03 - Creation

ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

-- PROCEDURE
CREATE OR REPLACE VIEW MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PROCEDURE AS (
SELECT OR_SURGICAL_CASE_IDENTIFIER    AS "or_surgical_case_identifier"
      ,OR_ENCOUNTER_IDENTIFIER        AS "encounter_identifier"
      ,CPT_CODE                       AS "cpt_code"
      ,CPT_DESCRIPTION                AS "cpt_description"
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_ANES_PROCEDURE
);

--SELECT *
--FROM MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PROCEDURE
--WHERE "or_surgical_case_identifier" = 'MAIN-2024-3835';

