-- MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PAIN.sql
-- RM 2025.02.05 - Creation

ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

-- PAIN
CREATE OR REPLACE VIEW MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PAIN AS (
SELECT OR_SURGICAL_CASE_IDENTIFIER            AS "or_surgical_case_identifier"
      ,OR_ENCOUNTER_IDENTIFIER                AS "encounter_identifier"
      ,PAIN_SCORE                             AS "pain_score"
      ,SUBSTRING(PAIN_SCORE_TS::STRING,1,19)  AS "pain_score_ts"
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_PAIN
);

--SELECT *
--FROM MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_PAIN
--WHERE "or_surgical_case_identifier" = 'MAIN-2024-3835';

