-- MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_STAFF.sql
-- RM 2025.01.31 - Creation

ALTER SESSION SET QUOTED_IDENTIFIERS_IGNORE_CASE = FALSE;

-- STAFF
CREATE OR REPLACE VIEW MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_STAFF AS (
SELECT OR_SURGICAL_CASE_IDENTIFIER  AS "or_surgical_case_identifier"
      ,OR_ENCOUNTER_IDENTIFIER      AS "or_encounter_identifier"
      ,STAFF_NAME                   AS "staff_name" 
      ,STAFF_ROLE                   AS "staff_role"
FROM MCHS_CUSTOM_DB.SPRUCE.SURGICAL_CASE_OR_STAFF
);

--SELECT *
--FROM MCHS_CUSTOM_DB.SPRUCE.VW_EXTRACT_STAFF
--WHERE "or_surgical_case_identifier" = 'MAIN-2024-3835';

